<?php

$title = 'Añadir una oficina';

$form = $this->form;

$form->prepare();

$gestorFormRow = $this->gestor_form_row();
?>
<div class="row">
    <div class="col-md-12">

        <div class="nav-tabs-custom">

            <div class="tab-content">
                <!-- <div class="box box-primary"> -->

                <!-- <div class="box box-primary"> -->
                <div class="box-header with-border">
                    <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
                    <br/><br/>


                    <div class="box-body">

                        <?php

                        echo $this->form()->openTag($form);

                        echo $gestorFormRow->render($form->get('numerooficina'));
                        echo $gestorFormRow->render($form->get('nombre'));
                        echo $gestorFormRow->render($form->get('direccion'));
                        echo $gestorFormRow->render($form->get('localidad'));
                        echo $gestorFormRow->render($form->get('idprovincia'));
                        echo $gestorFormRow->render($form->get('cp'));



                        ?>

                    </div>
                    <div class="box-footer">
                        <?php
                        $submitButton = $form->get('submit');
//                        echo $this->formHidden($form->get('id'));
//                        echo $this->formHidden($form->get('fecha_creacion'));
                        echo $this->formSubmit($submitButton);
                        ?>
                    </div>
                    <?php echo $this->form()->closeTag();?>
                </div>
            </div>
        </div>
    </div>
</div>