<?php

$title = 'Listado de oficinas';
$this->headTitle($title);

//var_dump($arrayOficinas);

?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
                <a class="pull-right" href="<?php echo $this->url('mastah/sections', array('section' => 'oficina','action'=>'add'));?>">Nueva</a>
            </div>

            <div class="box-body">

                <table class="table table-bordered table-hover">
                    <tr>
                        <th>Dirección</th>
                        <th>Localidad</th>
                        <th>Provincia</th>
                        <th>Código Postal</th>
                        <th>Número de Oficina</th>
                        <th class="text-center">Editar</th>
                        <th class="text-center">Activar/Desactivar</th>
                    </tr>

                    <?php foreach ($arrayOficinas as  $i => $entrada) {

                        echo("<tr>");
                        echo("<td>" . $entrada->direccion . "</td>");
                        echo("<td>" . $entrada->localidad . "</td>");
                        echo("<td>" . $entrada->nombreprovincia . "</td>");
                        echo("<td>" . $entrada->cp . "</td>");
                        echo("<td>" . $entrada->numerooficina . "</td>");

                        ?>
                        <td class="text-center">
                            <?php
                            $href = $this->url('mastah/sections', array(
                                'section' => 'oficina',
                                'action' => 'edit',
                                'id' => $entrada->id
                            ));
                            ?>
                            <a href="<?php echo $href?>"><i class="fa fa-edit"></i> </a>
                        </td>

                        <td class="text-center">
                            <?php
                            // Solo vamos a dejar borrarlo si no está asignado a ningún lado
                            if ($entrada->activa == 1)
                            {
                                $href = $this->url('mastah/sections', array(
                                    'section' => 'oficina',
                                    'action' => 'desactivar',
                                    'id' => $entrada->id
                                ));

                                echo ("<a href='".$href."'>");
                                echo ("Desactivar");
                            } else {
                                $href = $this->url('mastah/sections', array(
                                    'section' => 'oficina',
                                    'action' => 'activar',
                                    'id' => $entrada->id
                                ));
                                echo ("<a href='".$href."'>");
                                echo ("Activar");
                            }
                            echo ("</a>");
                            ?>


                        </td>

                        <?php

                        echo("</tr>");

                    }
                    ?>

                </table>

            </div>

        </div>
    </div>
</div>

