<?php

$title = 'Editar mis datos personales';
$this->headTitle($title);

//var_dump($arrayOficinas);

?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>



            <div class="box-body">
                <div class="callout callout-danger">
                    <h4>
                        No puedes hacer uso de esta sección.
                    </h4>
                    <br/>
                    <p>
                        Esta sección es solo para coordinadores y directores de relación.
                    </p>
                </div>
            </div>

        </div>
    </div>
</div>
