<?php
$contact = $menu->rows['contact']->id;
?>
<div class="row nav-breadcrumb hidden-xs">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?=$this->url($lang)?>">Home</a></li>
            <li class="breadcrumb-item active"><?=$menu->locale->{$lang}[$contact]->name?></li>
        </ol>
    </div>
</div>

<div class="container contact">
    <article>
        <div class="row">
            <div class="col-md-12">
                <h1><?=$menu->locale->{$lang}[$contact]->name?></h1>

                <div class="row">
                    <div class="col-md-6">
                        <form role="form">
                            <div class="form-group">
                                <label for="name"><?=$this->translate('Form Name','frontend');?></label>
                                <input type="name" class="form-control" id="name">
                            </div>

                            <div class="form-group">
                                <label for="email"><?=$this->translate('Form Email','frontend');?></label>
                                <input type="email" class="form-control" id="email">
                            </div>

                            <div class="form-group">
                                <label for="phone"><?=$this->translate('Form Phone','frontend');?></label>
                                <input type="phone" class="form-control" id="phone">
                            </div>

                            <div class="form-group">
                                <label for="text"><?=$this->translate('Form Message','frontend');?></label>
                                <textarea class="form-control" id="text" rows="10"></textarea>
                            </div>

                            <button type="submit" class="btn btn-default"><?=$this->translate('Form Send','frontend');?></button>
                        </form>
                    </div>
                    <div class="col-md-6 contact-info">
                        <div class="row">
                            <div class="col-md-12">

                                <h4><?=$this->translate('Social Networks','frontend');?></h4>
                                <div class="contact-icons">
                                    <a href="http://www.twitter.com" target="_blank"><i class="fa fa-twitter"></i></a>
                                    <a href="http://www.facebook.com" target="_blank"><i class="fa fa-facebook-official"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="contact-icons">
                                    <h4><?=$this->translate('Form Phone','frontend');?></h4><a class="phone" href="tel:<?=$appData->locale->{$lang}->phone?>"><?=$appData->locale->{$lang}->phone?></a>
                                    <h4>Email</h4><a class="mail" href="mailto:<?=$appData->locale->{$lang}->email?>"><?=$appData->locale->{$lang}->email?></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>
</div>