<?php

/**
 * Generated by ZF2ModuleCreator
 */

namespace AmConfiguration;

use Zend\ModuleManager\Feature\AutoloaderProviderInterface;
use Zend\ModuleManager\Feature\ConfigProviderInterface;
use Zend\Mvc\MvcEvent;
use Zend\Validator\AbstractValidator;

class Module implements AutoloaderProviderInterface, ConfigProviderInterface
{

    /**
     * Returns configuration to merge with application configuration
     *
     * @return array|\Traversable
     */
    public function getConfig()
    {
        return include __DIR__ . '/config/module.config.php';
    }

    /**
     * Return an array for passing to Zend\Loader\AutoloaderFactory.
     *
     * @return array
     */
    public function getAutoloaderConfig()
    {
        return array(
            'Zend\Loader\StandardAutoloader' => array(
                'namespaces' => array(
                    // Autoload all classes from namespace 'AmHome' from '/am-home-module/AmHome/src/AmHome'
                    __NAMESPACE__ => __DIR__ . '/src/' . __NAMESPACE__,
                )
            )
        );
    }

    public function onBootstrap(MvcEvent $e)
    {
        $translator = $e->getApplication()->getServiceManager()->get('translator');

        $locale = $translator->getLocale();

        $translateFile = __DIR__."/language/$locale/Zend_Validate.php";
        $translateFile = str_replace('/',DIRECTORY_SEPARATOR,$translateFile);
        $translator->getTranslator()->addTranslationFile(
            'phpArray',
            $translateFile,
            'default',
            $locale);

        AbstractValidator::setDefaultTranslator($translator);
    }
}