<?php

//var_dump($directorRelacion);

$title = 'Creación de equipos para director de relación';

?>
<div class="row">
    <div class="col-md-12">

        <div class="nav-tabs-custom">

            <?php
            // Llamamos a este helper para que pinte las pestañas y seleccione la que queremos
            $this->DRPestanya(3, $directorRelacion->id, $cuantosEquipos);
            ?>


            <div class="tab-content">
                <!-- <div class="box box-primary"> -->

                <div class="box-header with-border">
                    <h3 class="box-title"><?php echo $this->escapeHtml($title); ?>
                        <i><?php echo ($directorRelacion->nombre.' '.$directorRelacion->apellido1.' '.$directorRelacion->apellido2); ?></i></h3>
                    <div class="box-body">

                        <table class="table table-bordered table-hover">

                         <tr>
                             <td colspan="3">
                        <?php
                            if ($cuantosEquipos == 0)
                            {
                                ?>
                                <div class="callout callout-danger">
                                    <p>
                                        Debe crear al menos un equipo para este Director de relación
                                    </p>
                                </div>
                                <?php
                            } else {
                                ?>
                                <h3 class="box-title">Seleccione los componentes del equipo</h3><br/>
                                <?php
                            }

                            // Si se ha tratado de añadir un equipo sin seleccionar todos sus componentes
                            if ($hayErrorSeleccione == 1) {
                                ?>
                                <br/>
                                <div class="callout callout-danger">
                                    <p>
                                        <strong>Error : </strong>Para crear un equipo es necesario seleccionar un miembro para todas y cada una de sus posiciones.
                                    </p>
                                </div>
                                <?php
                            }

                        ?>
                             </td>
                         </tr>




                            <form action="/director_relacion/crearequipos/<?php echo $directorRelacion->id; ?>"
                                  method="POST" class="form-horizontal" name="Gestor_Form_DirectorRelacionForm"
                                  id="Gestor_Form_DirectorRelacionForm"><div class='form-group'>

                            <?php
                            foreach ($arrayNombresEspecialidad as  $i => $especialidad) :
                                if ((($i-1) % 3) == 0)
                                {
                                    echo ("<tr>");
                                }
                                echo ("<td width='33%'>");
                                echo ("<p>");
                                echo (ucFirst($especialidad['nombreInterno']));
                                echo ("</p>");


//var_dump($arrayEspecialistas);
                                //echo ("<select name='especialidad".$unEspecialista->idespecialidad['id']."'>");
                                echo ("<select name='especialidad".$especialidad['id']."'>");

                                //$estosEspecialistas = $arrayEspecialistas[$i];
                                $idEspecialidad = $especialidad['id'];

                                $arrayUnaEspecialidad = $arrayEspecialistas[$idEspecialidad];
                                echo ("<option value='0'>Selecciona una opción</option>");
                                for ($j = 0; $j < count($arrayUnaEspecialidad); $j++)
                                {
//var_dump($arrayUnaEspecialidad);
                                    //echo ("<option value=''>".$unEspecialista->nombre." ".$unEspecialista->apellido1." ".$unEspecialista->apellido2."</option>");
                                    echo ("<option value='".$arrayUnaEspecialidad[$j]->id."'");
                                    if ($arrayUnaEspecialidad[$j]->id == $_REQUEST[('especialidad'.$especialidad['id'])]) { echo ('SELECTED="SELECTED"'); }
                                    echo (">");
                                    echo ($arrayUnaEspecialidad[$j]->nombre." ".$arrayUnaEspecialidad[$j]->apellido1.
                                        " ".$arrayUnaEspecialidad[$j]->apellido2."</option>");
                                }
                                //foreach ($estosEspecialistas as $n => $unEspecialista) :
                                //    echo ("<option value=''>".$unEspecialista->nombre." ".$unEspecialista->apellido1." ".$unEspecialista->apellido2."</option>");
                                //endforeach;

                                echo ("</select>");

                                echo ("</td>");
                                if (($i % 3) == 0)
                                {
                                    echo ("</tr>");
                                }
                            endforeach;
                            ?>


                        </div>
                        <div class="box-footer">
                            <tr><td colspan="3">

                            <input type="submit" name="submit" id="submitbutton" class="btn btn-primary" value="Añadir">

                            </td></tr>
                            </table>

                        </form>
                    </div>
                    <?php //echo $this->form()->closeTag();
                        ?>
                </div>

            </div>
        </div>
    </div>
</div>