<?php

$title = 'Edición de director de relación';

$form = $this->form;

$form->prepare();

$gestorFormRow = $this->gestor_form_row();
?>
<div class="row">
    <div class="col-md-12">

        <div class="nav-tabs-custom">

            <?php
            // Llamamos a este helper para que pinte las pestañas y seleccione la que queremos
            $this->DRPestanya(1, $directorRelacion->id, $cuantosEquipos);
            ?>

            <div class="tab-content">
                <!-- <div class="box box-primary"> -->

    <!-- <div class="box box-primary"> -->
    <div class="box-header with-border">
    <h3 class="box-title"><?php echo $this->escapeHtml($title); ?>
        <i><?php echo ($directorRelacion->nombre.' '.$directorRelacion->apellido1.' '.$directorRelacion->apellido2); ?></i></h3>

    <div class="box-body">

                    <?php

                    // Esto es que lo acabamos de añadir, así que pintamos este mensaje
                    if ($addOK == 1) {
                        $hrefDR = $this->url('mastah/sections', array(
                            'section' => 'director_relacion',
                            'action' => 'crearequipos',
                            'id' => $directorRelacion->id
                        ));
                        $hrefGuia = $this->url('mastah/sections', array(
                            'section' => 'home',
                            'action' => 'index',
                        ));
                        ?>
                        <div class="callout callout-success">
                            <h4>Acabas de crear al Director de Relación <?php
                                echo ($directorRelacion->nombre." ".$directorRelacion->apellido1." ".$directorRelacion->apellido2); ?></h4>
                            <p><a href="<?php echo $hrefGuia; ?>">Descarga la Guía de Uso (PDF)</a> para enviársela por correo electrónico.</p>
                            <p><a href="<?php echo $hrefDR; ?>">Pulsa aquí</a> para configurar sus equipos.</p>
                        </div>
                        <?php
                    } else{
                        echo ("<br/><br/>");
                    }

                    echo $this->form()->openTag($form);

                    ?>
                    <div class='form-group'>
                        <label class="col-sm-2&#x20;control-label" for="idcargo">Último acceso</label>
                        <div class='col-sm-10' style='vertical-align: bottom;'>
                            <input type="text" value="<?php echo $directorRelacion->ultimoLogin; ?>" class="form-control" readonly>
                        </div>
                    </div>

                    <?php

                    echo $gestorFormRow->render($form->get('login'));

                    echo $gestorFormRow->render($form->get('iddireccionregional'));
                    echo $gestorFormRow->render($form->get('nombre'));
                    echo $gestorFormRow->render($form->get('apellido1'));
                    echo $gestorFormRow->render($form->get('apellido2'));
                    echo $gestorFormRow->render($form->get('idcargo'));
                    echo $gestorFormRow->render($form->get('idoficina'));

                    echo $gestorFormRow->render($form->get('movil'));
                    echo $gestorFormRow->render($form->get('email'));



                    ?>
        <!--
                    <div class='form-group'>
                        <label class="col-sm-2&#x20;control-label" for="idcargo">Teléfono móvil</label>
                        <div class='col-sm-10' style='vertical-align: bottom;'>
                            <input type="text" value="<?php echo $directorRelacion->movil; ?>" class="form-control" readonly>
                        </div>
                    </div>

                    <div class='form-group'>
                        <label class="col-sm-2&#x20;control-label" for="idcargo">Email</label>
                        <div class='col-sm-10' style='vertical-align: bottom;'>
                            <input type="text" value="<?php echo $directorRelacion->emailDecrypted; ?>" class="form-control" readonly>
                        </div>
                    </div>
-->
                    <?php



                    ?>

                    </div>
                <div class="box-footer">
                    <?php
                    $submitButton = $form->get('submit');
                    echo $this->formHidden($form->get('id'));
                    echo $this->formHidden($form->get('fecha_creacion'));
                    echo $this->formSubmit($submitButton);
                    ?>
    </div>
        <?php echo $this->form()->closeTag();?>
    </div>
    </div>
    </div>
    </div>
</div>