<?php
$title = 'Listado de equipos para director de relación';
?>
<div class="row">
    <div class="col-md-12">
        <div class="nav-tabs-custom">
            <?php
            // Llamamos a este helper para que pinte las pestañas y seleccione la que queremos
            $this->DRPestanya(2, $directorRelacion->id, $cuantosEquipos);?>

            <div class="tab-content">
                <div class="box-header with-border">
                    <h3 class="box-title"><?php echo $this->escapeHtml($title); ?>
                    <i><?php echo ($directorRelacion->nombre.' '.$directorRelacion->apellido1.' '.$directorRelacion->apellido2); ?></i></h3>

                    <div class="box-body">
                        <?php if ($addTeamOK == 1):?>
                            <div class="callout callout-success">
                                <p>Nuevo equipo creado.</p>
                            </div>
                        <?php endif; ?>

                    <?php if ($cuantosEquipos == 0):?>
                        <div class="callout callout-danger">
                            <p>
                                No existen equipos asignados a este director de relación
                            </p>
                        </div>
                    <?php endif;
                    // Recorremos los equipos que tenemos
                    for ($i = 0; $i < $cuantosEquipos; $i++):
                        // Ahora por cada uno una collapsed box ?>
                    <div class="box box-default collapsed-box">
                        <div class="box-header with-border">
                            <h3 class="box-title">Equipo <?php echo ($i+1); ?></h3>
                            <div class="box-tools pull-right">
                                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                            </div><!-- /.box-tools -->
                        </div><!-- /.box-header -->
                        <div class="box-body">

                            <form method='post' action=''>
                            <!-- id del equipo -->
                                <input type='hidden' name='idequipo' value='<?php echo $arrayEquipos[$i]['id']; ?>'>

                                <!-- Equipo en sí -->
                                <?php
                                // Para cada uno vamos a pintar sus datos
                                // -------- $arrayEquipos[$i][1..n]['idespecialista'] vemos si coincide
                                // --------- vamos a listar todas las especialidades
                                foreach ($arrayNombresEspecialidad as  $n => $especialidad) :
                                    if ((($n-1) % 3) == 0):?>
                                    <div class='row'>
                                    <?php endif;
                                        // Asignamos este trozo a "$pintarPersona" porque tenemos que pintarlo DESPUES de la foto
                                        $pintarPersona = "<div class='col-sm-4 col-xs-4'>
                                                            <div class='box box-default'>
                                                                <div class='box-header text-center with-border'>
                                                                    <strong>".ucfirst($especialidad['nombreInterno'])."</strong>
                                                                </div>
                                                                <div class='box-body text-center'>
                                                                    <div class='row'>
                                                                        <div class='col-xs-12'>
                                                                            <select style='margin-bottom: 10px' name='especialidad".$especialidad['id']."'>
                                                                            %s
                                                                            </select>
                                                                        </div>
                                                                    </div>
                                                                    <div class='row'>
                                                                        <div class='col-xs-12'>
                                                                            <img style='margin:0 auto;' class='img-responsive' src='%s' />
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                          </div>";

                                        $idEspecialidad = $especialidad['id'];

                                        $arrayUnaEspecialidad = $arrayEspecialistas[$idEspecialidad];
                                        $fotoTemp = '';
                                        $options = '';
                                        foreach ($arrayUnaEspecialidad as $j => $unaEspecialidad) {
                                            if ($unaEspecialidad->id == $arrayEquipos[$i][$n]['idespecialista']) {
                                                $options.= "<option value='".$unaEspecialidad->id."' selected='selected'>"
                                                    .$unaEspecialidad->nombre." ".$unaEspecialidad->apellido1.
                                                    " ".$unaEspecialidad->apellido2."</option>";

                                                $fotoTemp = $unaEspecialidad->foto;

                                            } else {
                                                $options.= "<option value='".$unaEspecialidad->id."'>"
                                                    .$unaEspecialidad->nombre." ".$unaEspecialidad->apellido1.
                                                    " ".$unaEspecialidad->apellido2."</option>";
                                            }
                                        }

                                        // Metemos la imagen para que se vea que existe
                                        $path = '/upload/especialista/';
                                        $pathCompleto = $path . $fotoTemp;
                                        // Sacamos el thumb que es el que queremos montar
                                        $pathCompleto = substr($pathCompleto, 0, strlen($pathCompleto) - 4) . "_thumb" . substr($pathCompleto, (strlen($pathCompleto) - 4), strlen($pathCompleto));

                                        $pintarPersona = sprintf($pintarPersona,$options,$pathCompleto);

                                        echo $pintarPersona; ?>
                                    <?php if (($n % 3) == 0) :?>
                                    </div>
                                    <?php endif;
                                endforeach;?>

                                <div class="box-footer">
                                    <input type="submit" name="submit" id="submitbutton" class="btn btn-primary" value="Guardar">
                                </div>
                            </form>
                            <!-- CERRAMOS The body of the box -->
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                    <?php endfor;?>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>