<?php

$title = 'Edición de datos de usuario';
$this->headTitle($title);

$form = $this->form;

$gestorFormRow = $this->gestor_form_row();

$form->prepare();
?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
                <br/>
                <br/>
                <h3 class="box-title" style="color: #dd0000;">Por favor, rellene sus datos para continuar.</h3>
                <br/>
                <br/>

            </div>
            <?php echo $this->form()->openTag($form);?>
            <div class="box-body">
                <?php if($message != ''):?>
                    <div class="alert alert-info alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert">x</button>
                        <h4>Aviso</h4>
                        <?=$message;?>
                    </div>
                <?php endif;?>
                <?php
                if ($userData->idPerfil != 1) {
                    echo $gestorFormRow->render($form->get('email'));
                }

                if ($userData->idPerfil == 3) {
                    echo $gestorFormRow->render($form->get('telefono'));
                }

                    echo $gestorFormRow->render($form->get('password'));
                    echo $gestorFormRow->render($form->get('password2'));
                ?>
            </div>
            <div class="box-footer">
                <?php
                $submitButton = $form->get('submit');
                echo $this->formSubmit($submitButton);
                ?>
            </div>
            <?php echo $this->form()->closeTag();?>
        </div>
    </div>
</div>