<p class="login-box-msg">Introduzca sus datos para iniciar sesión</p>
<?php
if(isset($userFound)):
    $message = $userFound ? 'Tu contraseña es: ' . $foundPassword : "Datos incorrectos";
    $alertType = $userFound ? 'alert-success' : 'alert-danger';
    ?>
    <div class="alert <?=$alertType;?> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <?=$message;?>
    </div>
<?php endif; ?>

<form method="post" action="/admin/login/check-login">
    <div class="form-group has-feedback">
        <input name="user" type="text" class="form-control" placeholder="Usuario">
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
    </div>
    <div class="form-group has-feedback">
        <input name="password" type="password" class="form-control" placeholder="Contraseña">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
    </div>
    <div class="row">
        <div class="col-xs-8">
            <!--<div class="checkbox icheck">
                <label>
                    <input type="checkbox"> Remember Me
                </label>
            </div>-->
        </div><!-- /.col -->
        <div class="col-xs-4">
            <input type="submit" class="btn btn-primary btn-block btn-flat" value="Entrar" />
        </div><!-- /.col -->
    </div>
    <div class="row">
        <div class="col-xs-12">
            <a href="/login/remember-password">¿Olvidó su contraseña?</a>
        </div>
    </div>
    <?php if ($this->flashMessenger()->hasMessages()) :
        $messages = $this->flashMessenger()->getMessages();
        foreach ($messages as $msg): ?>
            <div class='error_login'><?php echo $msg?></div>
        <?php endforeach; ?>
    <?php endif; ?>
</form>