<p class="login-box-msg">Introduzca los datos con los que accede a la plataforma</p>

<?php
if(isset($userFound)):
    $message = $userFound ? 'Tu contraseña es: ' . $password : "Datos incorrectos";
    $alertType = $userFound ? 'alert-success' : 'alert-danger';
    ?>
    <div class="alert <?=$alertType;?> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <?=$message;?>
    </div>
<?php endif;

$title = 'Recordar password';
$this->headTitle($title);

$form = $this->form;

$gestorFormRow = $this->gestor_form_row();

$form->prepare();

echo $this->form()->openTag($form);
echo $gestorFormRow->render($form->get('username'));
echo $gestorFormRow->render($form->get('email')); ?>
<div class="col-md-offset-9">
    <?php echo $gestorFormRow->render($form->get('submit'));?>
</div>
<?php echo $this->form()->closeTag();?>
<br/>
<a class="text-center" href="/login">Volver a login</a>