<?php
$jobMenuId         = $this->menu->rows['jobs']->id;
$images = json_decode($this->job->imageUrl);
$carouselHelper = $this->carouselItemHelper();
?>
<div class="row nav-breadcrumb hidden-xs">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?=$this->url('locale', ['locale' => $this->lang])?>">Home</a></li>
            <li class="breadcrumb-item"><a href="<?=$this->url('locale/jobs', ['locale' => $this->lang])?>"><?=$this->menu->locale->{$lang}[$jobMenuId]->name?></a></li>
            <li class="breadcrumb-item"><a href="<?=$this->url('locale/jobs/category',array('locale' => $this->lang, 'category' => $this->currentCategory['urlKey']))?>"><?=$this->currentCategory['title']?></a></li>
            <li class="breadcrumb-item active"><?=$this->job->title;?></li>
        </ol>
    </div>
</div>

<div class="container jobs detail">
    <article>
        <div class="row">
            <div class="col-md-12">
                <h1><?=$this->job->title;?></h1>
                <?=$this->job->content;?>
                <div class="wrapper">
                    <div class="masonry bordered" id="gallery">
                        <?php echo $carouselHelper->render($images)?>
                    </div>
                </div>
                <?php $this->facebookShareHelper()->render();?>
            </div>
        </div>
    </article>

</div>