<style>
    .video-controls {
        position: absolute;
        bottom: 5px;
        width: 100%;
        right:0;
        color: white;
        font-size: 25px;
        background: url(../../../../img/black-0.5.png) repeat;
        padding: 10px;
    }

    .video-controls i {
        cursor: pointer;
    }

    .video-controls.hide-control{
        right: -100%;
    }
</style>
<?php
$jobMenuId         = $menu->rows['jobs']->id;
$images = json_decode($job->imageUrl);
$carouselHelper = $this->carouselItemHelper();
?>
<div class="row nav-breadcrumb hidden-xs">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?=$this->url($lang)?>">Home</a></li>
            <li class="breadcrumb-item"><a href="<?=$this->url($lang.'/jobs')?>"><?=$menu->locale->{$lang}[$jobMenuId]->name?></a></li>
            <li class="breadcrumb-item"><a href="<?=$this->url($lang.'/jobs/category',array('category' => $currentCategory['urlKey']))?>"><?=$currentCategory['title']?></a></li>
            <li class="breadcrumb-item active"><?=$job->title;?></li>
        </ol>
    </div>
</div>

<div class="container jobs detail">
    <article>
        <div class="row">
            <div class="col-md-12">
                <h1><?=$job->title;?></h1>
                <?=$job->content;?>
                <div id="owl_carousel">
                    <?php echo $carouselHelper->render($images)?>
                </div>
            </div>
        </div>
    </article>

</div>