<?php
$jobMenuId         = $this->menu->rows['jobs']->id;
$galleryHelper         = $this->galleryHelper();
$jobCategoryHelper = $this->jobCategoryHelper();
?>
<div class="row nav-breadcrumb hidden-xs">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?=$this->url('locale', ['locale' => $this->lang])?>">Home</a></li>
            <?php if(!isset($currentCategory)):?>
                <li class="breadcrumb-item active"><?=$this->menu->locale->{$this->lang}[$jobMenuId]->name?></li>
            <?php else :?>
                <li class="breadcrumb-item"><a href="<?=$this->url('locale/jobs', ['locale' => $this->lang])?>"><?=$this->menu->locale->{$this->lang}[$jobMenuId]->name?></a></li>
                <li class="breadcrumb-item active"><?=$currentCategory['title']?></a></li>
            <?php endif?>
        </ol>
    </div>
</div>

<div class="container jobs">

    <article>

        <div class="row">
            <div class="col-md-9">

                <header>
                    <h1><?=$this->menu->locale->{$this->lang}[$jobMenuId]->name?></h1>
                    <?php if(isset($currentCategory)):?>
                        <h2><?=$currentCategory['title']?></h2>
                    <?php endif?>
                </header>

                <div class="row intro-section">
                    <div class="col-xs-12">
                        <?php if(isset($currentCategory)):?>
                            <?=$currentCategory['content'];?>
                        <?php else :?>
                            <?=$this->menu->locale->{$this->lang}[$jobMenuId]->content;?>
                        <?php endif?>
                    </div>
                </div>

                <div class="row">
                    <?php $galleryHelper->render($this->lang, $this->jobs);?>
                </div>
            </div>
            <aside class="col-md-3">
                <h3>Categorias</h3>
                <ul>
                    <?php $jobCategoryHelper->render($this->lang,$this->jobCategories);?>
                </ul>
            </aside>
        </div>

        <div class="row">
            <div class="col-md-12">
                <?php
                // add at the end of the file after the table
                echo $this->paginationControl(
                // the paginator object
                    $this->jobs,
                    // the scrolling style
                    'sliding',
                    // the partial to use to render the control
                    'partial/paginator.phtml',
                    // the route to link to when a user clicks a control link
                    array(
                        'route' => $this->routePagination,
                        'routeParams' => $this->routeParams
                    )
                );
                ?>
            </div>
        </div>

    </article>

</div>