<?php if ($this->pageCount): ?>
    <ul class="pagination float-right">
        <?php if (isset($this->previous)): ?>
            <li class="page-item">
                <a class="page-link" href="<?php echo $this->url($this->route,$this->routeParams); ?>?page=<?php echo $this->previous; ?>"><i class="fas fa-angle-left"></i></a>
            </li>
        <?php else: ?>
            <li class="disabled">
                <li class="page-item"><a class="page-link"><i class="fas fa-angle-left"></i></a></li>
            </li>
        <?php endif; ?>

        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li class="page-item">
                    <a class="page-link" href="<?php echo $this->url($this->route,$this->routeParams);?>?page=<?php echo $page; ?>">
                        <?php echo $page; ?>
                    </a>
                </li>
            <?php else: ?>
                <li class="page-item active">
                    <a class="page-link" href="#">
                        <?php echo $page; ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if (isset($this->next)): ?>
            <li class="page-item">
                <a class="page-link" href="<?php echo $this->url($this->route,$this->routeParams); ?>?page=<?php echo $this->next; ?>"><i class="fas fa-angle-right"></i></a>
            </li>
        <?php else: ?>
            <li class="disabled">
                <li class="page-item"><a class="page-link"><i class="fas fa-angle-right"></i></a></li>
            </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>