<?php

/**
 * VARIABLES DISPONIBLES
 *      $this (es una instancia de zend-view/src/Renderer/PhpRenderer.php)
 *      $element
 *      $label
 *      $labelAttributes
 *      $labelPosition
 *      $renderErrors
 */

$imagesUrl = $element->getValue();

$html = '';

$formInput = $this->formInput();
$element->setName($element->getName());
$element->setAttribute('data-is-multiple','0');
$row = "<div class = 'form-group'><div class='col-xs-12'>%s</div></div>";

$id = $element->getAttribute('id');
$element->setAttribute('data-id',$id);
if (is_array($imagesUrl)) {
    foreach ($imagesUrl as $index => $url) {
        $element->setValue($url);

        $element->setAttribute('id',$id.$index);
        $element->setAttribute('data-index',$index);

        $html .= sprintf($row,$formInput->render($element));
    }
} elseif(is_string($imagesUrl)) {
    $html .= sprintf($row,$formInput->render($element));
} else {
    $element->setValue('');
    $element->setAttribute('id',$id."0");
    $element->setAttribute('data-index',"0");
    $html .= sprintf($row,$formInput->render($element));
}

echo $html;