<?php
$basePath = $this->basePath() . '/administrator';

echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.jpg'))
        ->appendStylesheet($basePath . '/libs/bootstrap/css/bootstrap.min.css')
        ->appendStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css')
        ->appendStylesheet('https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css')
        ->appendStylesheet($basePath . '/css/AdminLTE.min.css')
        ->appendStylesheet($basePath . '/libs/iCheck/square/blue.css')
        ->appendStylesheet($basePath . '/css/style.css')
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->appendFile($basePath . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ->appendFile($basePath . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
</head>

<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <!--ABS Consultor-->
        <img width="200" src="/img/white-logo-horizontal.png"/>
    </div><!-- /.login-logo -->
    <div class="login-box-body">
        <?php echo $this->content; ?>
    </div><!-- /.login-box-body -->
</div><!-- /.login-box -->

<?php echo $this->headScript()
    ->appendFile($basePath . '/libs/jQuery/jQuery-2.1.4.min.js')
    ->appendFile($basePath . '/libs/bootstrap/js/bootstrap.min.js')
;?>
</body>
</html>
