<?php
echo $this->doctype();
$basePath = $this->basePath() . '/administrator';
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $basePath . '/img/favicon.ico'))


        ->prependStylesheet($basePath . '/css/style.css')
        ->prependStylesheet($basePath . '/css/skins/skin-blue.min.css')
        ->prependStylesheet($basePath . '/css/AdminLTE.min.css')
        ->prependStylesheet($basePath . '/libs/select2/css/select2.min.css')
        ->prependStylesheet($basePath . '/libs/font-awesome/css/font-awesome.min.css')
        ->prependStylesheet($basePath . '/libs/bootstrap/css/bootstrap.min.css')

    ?>
</head>
<body>
<div class="wrapper">

    <!-- Your Page Content Here -->
    <?php echo $this->content; ?>

</div>

<!-- Scripts -->
<?php echo $this->headScript()

    ->prependFile($basePath . '/libs/jQueryUI/jQuery-ui.min.js')
    ->prependFile($basePath . '/libs/jQuery/jQuery-2.1.4.min.js')
;

?>
<?php echo $this->inlineScript(); ?>
</body>
</html>