<?php

$title = 'Edit Menu entry';
$this->headTitle($title);

$form = $this->form;

$gestorFormRow = $this->administrator_form_row();

$form->prepare();
?>

<div class="row">
    <div class="col-sm-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <?php echo $this->form()->openTag($form);?>
            <?php
            echo $this->form()->openTag($form);
            echo $gestorFormRow->render($form);
            echo $this->form()->closeTag();
            ?>
            <?php echo $this->form()->closeTag();?>
        </div>
    </div>
</div>