<style>
    ul.navigation-menu, ul.navigation-menu li ul {
        list-style-type: none;
    }

    ul.navigation-menu {
        padding-left: 0;
    }

    ul.navigation-menu li {
        padding: 3px 0;
    }

    ul.navigation-menu li.add-more {
        padding-top: 0px;
    }
</style>
<?php

$title = 'Navigation Menu';
$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<ul class="navigation-menu">
<?php foreach ($entradas as  $i => $entrada) :?>
    <li>
        <?=$entrada->texto;?>
        <a class="btn" href="<?php echo $this->url('administrator',array('module' => 'menu','action'=>'edit', 'id' => $entrada->id));?>"><i class="fa fa-edit"></i></a>

        <?php if (count($entrada->hijos) > 0) :?>
            <ul>
                <?php foreach ($entrada->hijos as $k => $hijo) :?>
                <li>
                    <a class="btn" href="<?php echo $this->url('administrator', array('module' => 'menu','action' => 'delete', 'id' => $hijo->id));?>"><i class="fa fa-remove"></i></a>
                    <a class="btn" href="<?php echo $this->url('administrator', array('module' => 'menu','action' => 'edit', 'id' => $hijo->id));?>"><i class="fa fa-edit"></i></a>
                    <?=$hijo->texto;?>
                </li>
                <?php endforeach; ?>
                <li class="add-more"><a class="btn" href="<?php echo $this->url('administrator', array('module' => 'menu', 'action' => 'add', 'id' => $entrada->id, 'data' => ($k + 1)));?>"><i class="fa fa-plus"></i></a></li>
            </ul>

        <?php else:?>
        <a class="btn" href="<?php echo $this->url('administrator', array('module' => 'menu','action'=>'delete', 'id' => $entrada->id));?>"><i class="fa fa-remove"></i></a>
        </li>
        <li><ul><li class="add-more"><a href="<?php echo $this->url('administrator',array('module' => 'menu','action'=>'add', 'id' => $entrada->id, 'data' => ($i + 1)));?>"><i class="fa fa-plus"></i></a></li></li></ul>

    <?php endif; ?>
    </li>
<?php endforeach ?>

</ul>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="<?php echo $this->url('administrator',
    array('module' => 'menu','action'=>'add', 'id' => 0, 'data' => ($i+1)));?>">Add Menu</a>