<?php

$title = 'Add user';
$this->headTitle($title);

$form = $this->form;

$gestorFormRow = $this->administrator_form_row();

$form->prepare();

?>

<div class="row">
    <?php if(count($messages)):?>
        <div class="col-md-12">
            <div class="alert alert-warning alert-dismissable">
                <?php foreach ($messages as $message) :?>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i> Alert!</h4>
                    <?= $message; ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif;?>
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <?php
            echo $this->form()->openTag($form);
            echo $gestorFormRow->render($form);
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>