<?php
$partnerMenuId = $this->menu->rows['company/colaborators']->id;
$company = $this->menu->rows['company']->id;

$partnerHelper = $this->partnerHelper($this->lang);

?>
<div class="row nav-breadcrumb hidden-xs">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?=$this->url('locale', ['locale' => $this->lang])?>">Home</a></li>
            <li class="breadcrumb-item active"><?=$this->menu->locale->{$this->lang}[$company]->name?></li>
        </ol>
    </div>
</div>

<div class="container company">

    <article>

        <h1><?=$this->menu->locale->{$this->lang}[$company]->name?></h1>

        <?=$this->menu->locale->{$this->lang}[$company]->content?>

        <!--<img class="img-responsive" src="/media/maqueta/company1.png" />-->

    </article>

    <?php if(isset($partners)):?>

    <h3><?=$this->translate('Our Partners','frontend');?></h3>

    <div id="collaborators_carousel">

        <?php $partnerHelper->render($partners); ?>

    </div>
    <?php endif; ?>
</div>