<?php

/**
 * VARIABLES DISPONIBLES
 *      $this (es una instancia de zend-view/src/Renderer/PhpRenderer.php)
 *      $element
 *      $label
 *      $labelAttributes
 *      $labelPosition
 *      $renderErrors
 */

$imagesUrl = $this->element->getValue();

$html = '';

$formInput = $this->formInput();
$this->element->setName($this->element->getName().'[]');
$this->element->setAttribute('data-is-multiple','1');
$row = "<div class = 'form-group'><div class='col-xs-12'>%s</div></div>";

$id = $this->element->getAttribute('id');
$this->element->setAttribute('data-id',$id);
if (count($imagesUrl)) {
    foreach ($imagesUrl as $index => $url) {
        $this->element->setValue($url);

        $this->element->setAttribute('id',$id.$index);
        $this->element->setAttribute('data-index',$index);

        $html .= sprintf($row,$formInput->render($this->element));
    }
} else {
    $this->element->setValue('');
    $this->element->setAttribute('id',$id."0");
    $this->element->setAttribute('data-index',"0");
    $html .= sprintf($row,$formInput->render($this->element));
}

echo $html . '<input type = "button" class="pull-right btn btn-info btn-flat allow_multiple_files" value="Nueva imagen" data-value="'.$id.'" />';