<?php

$title = 'List Modules';
$this->headTitle($title);

?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>

            <div class="box-body">
                <?php if ((isset($modules)) && (count($modules) > 0)) :?>
                    <table class="table table-bordered table-hover">
                        <tr>
                            <th>Ruta en Zend</th>
                            <th>Nombre público</th>
                            <th colspan="2" class="text-center">Acciones</th>
                        </tr>

                        <?php foreach ($modules as $elemento) :
                            $urlToEdit = $this->url('administrator', array('module' => 'module','action'=>'edit', 'id' => $elemento->id));
                            $urlToDelete = $this->url('administrator', array('module' => 'module','action'=>'delete', 'id' => $elemento->id));?>

                            <tr>
                                <td><?=$elemento->nombreZend; ?></td>
                                <td><?=$elemento->nombreUsable; ?></td>
                                <td class="text-center"><a title="edit" href="<?php echo $urlToEdit;?>"><i class="fa fa-edit"></i></a></td>
                                <td class="text-center"><a title="delete" href="<?php echo $urlToDelete;?>"><i class="fa fa-remove"></i></a></td>
                            </tr>

                        <?php endforeach; ?>
                    </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>