<?php
$colaborators = $menu->rows['company/colaborators']->id;
$company = $menu->rows['company']->id;

$colaboratorUrl = $this->url($lang.'/company/colaborators',array(
    'lang' => $lang,
    'section' => $menu->locale->{$lang}[$company]->urlKey,
    'colaborators' => $menu->locale->{$lang}[$colaborators]->urlKey
));
?>
<div class="row nav-breadcrumb hidden-xs">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?=$this->url($lang)?>">Home</a></li>
            <li class="breadcrumb-item active"><?=$menu->locale->{$lang}[$company]->name?></li>
        </ol>
    </div>
</div>

<div class="container company">

    <article>

        <h1><?=$menu->locale->{$lang}[$company]->name?></h1>

        <?=$menu->locale->{$lang}[$company]->content?>

        <!--<img class="img-responsive" src="/media/maqueta/company1.png" />-->

    </article>

    <h3><a href="<?=$colaboratorUrl;?>"><?=$this->translate('Our Partners','frontend');?></a></h3>

    <div id="collaborators_carousel">

        <div class="item">
            <a href="/empresa/colaboradores#collab1"><img src="/media/maqueta/collab1.png" alt="Collab"></a>
        </div>
        <div class="item">
            <a href="/empresa/colaboradores#collab2"><img src="/media/maqueta/collab2.png" alt="Collab"></a>
        </div>
        <div class="item">
            <a href="/empresa/colaboradores#collab3"><img src="/media/maqueta/collab3.png" alt="Collab"></a>
        </div>
        <div class="item">
            <a href="/empresa/colaboradores#collab4"><img src="/media/maqueta/collab4.png" alt="Collab"></a>
        </div>

    </div>
</div>