<br/>
<?php if ($esAdmin == 1) :?>

    <tr><td colspan="2">El perfil es de tipo administrador y tiene permiso para acceder a todos los recursos.</td></tr>

<?php else: ?>

    <?php
        $count = 0;
        foreach($listaControladores as $controlador) :
        $count++; ?>
        <tr>
            <td><?php echo $controlador->nombreUsable;?></td>
            <td>
                <?php
                // Y ahora vemos si tiene permiso o no.
                $checked = "";
                if (isset($listaPermisos[$idPerfil]) and array_key_exists($controlador->id,$listaPermisos[$idPerfil])) {
                    $checked = "checked = 'checked'";
                }
                ?>
                <input name='permisos[]' value='<?php echo $controlador->id?>' type='checkbox' <?php echo $checked?>/>
            </td>
        </tr>
    <?php endforeach;

    if ($count == 0)
    {   ?>
        <span class="rojo">No hay controladores o el padre de este perfil no tiene ningún permiso asignado.</span>
        <br/><br/>
        <?php
    }
    ?>


    <tr>
        <td>
            <input type="hidden" name="idPerfil" value="<?php echo $idPerfil; ?>">
            <input type="submit" value="Grabar">
        </td>
    </tr>

<?php endif; ?>