<div class="container-fluid home">
    <div class="row">
        <div class="video-wrapper">
            <video width="100%" autoplay loop>
                <source src="/media/video/grua.mp4" type="video/mp4"/>
            </video>
            <div class="video-filter"></div>
        </div>
    </div>
</div>

<hr>

<div class="container">
    <div class="row home-module">
        <div class="col-md-6 col-xs-12">
            <img class="img-responsive" src="media/maqueta/home1.png" />
        </div>
        <div class="col-md-6 col-xs-12">
            <h2>Empresa</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id nunc convallis, accumsan enim ac, convallis risus.
                Aliquam facilisis mi lectus, nec vestibulum ipsum vestibulum nec. Curabitur tincidunt ultricies nisi eu mattis.
                Donec blandit vitae mi vitae commodo. Ut tortor dui, vulputate et nunc et, suscipit vestibulum ipsum.
            </p>
            <a class="btn btn-default">+ Información</a>
        </div>
    </div>
    <div class="row home-module">
        <div class="col-md-6 col-xs-12">
            <h2>Trabajos</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id nunc convallis, accumsan enim ac, convallis risus.
                Aliquam facilisis mi lectus, nec vestibulum ipsum vestibulum nec. Curabitur tincidunt ultricies nisi eu mattis.
                Donec blandit vitae mi vitae commodo. Ut tortor dui, vulputate et nunc et, suscipit vestibulum ipsum.
            </p>
            <a class="btn btn-default">+ Información</a>
        </div>
        <div class="col-md-6 col-xs-12">
            <img class="img-responsive" src="media/maqueta/home2.png" />
        </div>
    </div>
    <div class="row home-module">
        <div class="col-md-6 col-xs-12">
            <img class="img-responsive" src="media/maqueta/home3.png" />
        </div>
        <div class="col-md-6 col-xs-12">
            <h2>Blog</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id nunc convallis, accumsan enim ac, convallis risus.
                Aliquam facilisis mi lectus, nec vestibulum ipsum vestibulum nec. Curabitur tincidunt ultricies nisi eu mattis.
                Donec blandit vitae mi vitae commodo. Ut tortor dui, vulputate et nunc et, suscipit vestibulum ipsum.
            </p>
            <a class="btn btn-default">+ Información</a>
        </div>
    </div>
</div>