<?php
$menuHelper = $this->applicationMenuHelper();

$this->headLink()->appendStylesheet($this->basePath('absconsultor/css/home.css'))
?>
<div class="container-fluid home">
    <div class="row">
        <ul class="bxslider">
            <li>
                <img src="/media/maqueta/company1.png" />
                <div class="video-filter"></div>
            </li>
            <li>
                <div class="video-wrapper">
                    <video class="video" width="100%">
                        <source src="/media/video/grua.mp4" type="video/mp4"/>
                    </video>
                    <div class="video-filter">
                        <div class="video-controls">
                            <i class="fa fa-play"></i>
                            <i class="fa fa-pause hide"></i>
                        </div>
                    </div>
                </div>
            </li>
        </ul>

        <img id="home_brand_logo" src="<?php echo $this->basePath('img/white-logo.png') ?>" alt="Logo ABS Consultor" class="transition brand-logo"/>
        <ul class="nav home-navbar navbar-nav transition">
            <?=$menuHelper->render($menu,$lang);?>
        </ul>

        <div class="col-xs-12 hidden-sm hidden-xs">
            <i class="fa fa-chevron-down transition"></i>
        </div>
        <!--<div class="video-wrapper">
            <video width="100%" autoplay loop>
                <source src="http://absconsultor.local:8080/media/video/grua.mp4" type="video/mp4"/>
            </video>
            <div class="video-filter"></div>
            <img id="home_brand_logo" src="<?php /*echo $this->basePath('img/white-logo.png') */?>" alt="Logo ABS Consultor" class="transition"/>
            <ul class="nav navbar-nav transition">
                <li><a href="/empresa">Empresa</a></li>
                <li><a href="/trabajos">Trabajos</a></li>
                <li><a href="/blog">Blog</a></li>
                <li><a href="/contacto">Contacto</a></li>
            </ul>
        </div>-->
    </div>
</div>

<hr>

<div class="container">
    <div class="row home-module">
        <div class="col-md-6 col-xs-12">
            <div class="owl-carousel-home">
                <div class="item">
                    <img class="img-responsive" src="media/maqueta/home1.png" />
                </div>
                <div class="item">
                    <img class="img-responsive" src="media/maqueta/home1.png" />
                </div>
                <div class="item">
                    <img class="img-responsive" src="media/maqueta/home1.png" />
                </div>
                <div class="item">
                    <img class="img-responsive" src="media/maqueta/home1.png" />
                </div>
            </div>
        </div>
        <div class="col-md-6 col-xs-12">
            <h2>Empresa</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id nunc convallis, accumsan enim ac, convallis risus.
                Aliquam facilisis mi lectus, nec vestibulum ipsum vestibulum nec. Curabitur tincidunt ultricies nisi eu mattis.
                Donec blandit vitae mi vitae commodo. Ut tortor dui, vulputate et nunc et, suscipit vestibulum ipsum.
            </p>
            <a class="btn btn-default">+ Información</a>
        </div>
    </div>
    <div class="row home-module">
        <div class="col-md-6 col-md-push-6 col-xs-12">
            <div class="owl-carousel-home">
                <div class="item">
                    <img class="img-responsive" src="media/maqueta/home2.png" />
                </div>
                <div class="item">
                    <img class="img-responsive" src="media/maqueta/home2.png" />
                </div>
                <div class="item">
                    <img class="img-responsive" src="media/maqueta/home2.png" />
                </div>
                <div class="item">
                    <img class="img-responsive" src="media/maqueta/home2.png" />
                </div>
            </div>
        </div>
        <div class="col-md-6 col-md-pull-6 col-xs-12">
            <h2>Trabajos</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id nunc convallis, accumsan enim ac, convallis risus.
                Aliquam facilisis mi lectus, nec vestibulum ipsum vestibulum nec. Curabitur tincidunt ultricies nisi eu mattis.
                Donec blandit vitae mi vitae commodo. Ut tortor dui, vulputate et nunc et, suscipit vestibulum ipsum.
            </p>
            <a class="btn btn-default">+ Información</a>
        </div>
    </div>
    <div class="row home-module">
        <div class="col-md-6 col-xs-12">
            <img class="img-responsive" src="media/maqueta/home3.png" />
        </div>
        <div class="col-md-6 col-xs-12">
            <h2>Blog</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id nunc convallis, accumsan enim ac, convallis risus.
                Aliquam facilisis mi lectus, nec vestibulum ipsum vestibulum nec. Curabitur tincidunt ultricies nisi eu mattis.
                Donec blandit vitae mi vitae commodo. Ut tortor dui, vulputate et nunc et, suscipit vestibulum ipsum.
            </p>
            <a class="btn btn-default">+ Información</a>
        </div>
    </div>
</div>