<?php
$basePath = $this->basePath() . '/administrator/libs/';

$this->headScript()->appendFile($basePath . "ckeditor/ckeditor.js");

$this->headTitle($this->title);

$form = $this->form;

$gestorFormRow = $this->administrator_form_row();

$form->prepare();

?>

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <?php
            echo $this->form()->openTag($form);
            echo $gestorFormRow->render($form);
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>

<?=$blocks?>