<?php


$this->headTitle($title);

?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
                <?php if (isset($add_action)):?>
                    <a class="pull-right btn btn-app" href="<?=$add_action?>"><i class="fa fa-plus"></i>Nuevo</a>
                <?php endif;?>

                <?php if (isset($export_action)):?>
                    <a class="pull-right btn btn-app" href="<?=$export_action?>"><i class="fa fa-file-excel-o"></i> Exportar listado</a>
                <?php endif;?>
            </div>

            <div class="box-body">
                <?php
                /**
                 * NO BORRAR LAS ETIQUETAS DE LA SIGUIENTE TABLA.
                 * SON NECESARIAS PARA QUE EL PLUGIN DATATABLES FUNCIONE CORRECTAMENTE
                 */
                ?>
                <table data-settings='<?=json_encode($settings);?>' class="datatable table table-bordered table-hover" id="<?=$table_id?>">
                    <thead>
                        <tr></tr>
                        <tr></tr>
                    </thead>

                    <tbody>
                    </tbody>

                    <tfoot>
                        <tr></tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="datatable_modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal Default</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->