<?php

/**
 * Generated by ZF2ModuleCreator
 */

return array(

    'view_manager' => array(
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),

    'controllers' => array(
        'invokables' => array(
            'AmConfiguration\Controller\AmConfigurationModuleController' => 'AmConfiguration\Controller\AmConfigurationModuleController'
        )
    ),

    'service_manager' => array(

    ),

    'router' => array(

    )
);