<?php

$title = 'Añadir un especialista';

$form = $this->form;

$form->prepare();

$gestorFormRow = $this->gestor_form_row();

?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>


                <div class="box-body">

                        <?php
                        echo $this->form()->openTag($form);

                        echo $gestorFormRow->render($form->get('idespecialidad'));
                        echo $gestorFormRow->render($form->get('nombre'));
                        echo $gestorFormRow->render($form->get('apellido1'));
                        echo $gestorFormRow->render($form->get('apellido2'));

                        echo $gestorFormRow->render($form->get('foto'));

                        ?>
                    </div>
                    <div class="box-footer">
                        <?php

                        $submitButton = $form->get('submit');
                        echo $this->formSubmit($submitButton);
                        ?>

                </h3>
            </div>
        </div>
    </div>
</div>