<?php

$title = 'Edición de especialista';

$form = $this->form;

$form->prepare();

$gestorFormRow = $this->gestor_form_row();
?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>


                <div class="box-body">

                    <?php

                    echo $this->form()->openTag($form);

                    // Solo vamos a dejar que cambie la especialidad si el especialista no tiene equipos
                    if (count($equiposEspecialista) == 0)
                    {
                        echo $gestorFormRow->render($form->get('idespecialidad'));
                    } else {
                        ?>
                        <div class='form-group'>
                        <label class="col-sm-2&#x20;control-label" for="nombre">Especialidad</label>
                        <div class='col-sm-10'>
                            <input type="text" value="<?php echo $miEspecialidad->nombreInterno; ?> (Solo puede cambiarse si el especialista no tiene equipos asignados)" class="form-control" readonly>
                        </div>
                        </div>
                        <?php
                    }
                    echo $gestorFormRow->render($form->get('nombre'));
                    echo $gestorFormRow->render($form->get('apellido1'));
                    echo $gestorFormRow->render($form->get('apellido2'));
            //var_dump($form->get('foto')->getValue());
            //var_dump(get_class_methods($form->get('foto')));
                    if (($form->get('foto')->getValue() != '') && (($form->get('foto')->getValue() != null)))
                    {
                        // Metemos la imagen para que se vea que existe
                        $path = '/upload/especialista/';
                        $pathCompleto = $path.$form->get('foto')->getValue();
                        // Sacamos el thumb que es el que queremos montar
                        $pathCompleto = substr($pathCompleto, 0, strlen($pathCompleto) - 4)."_thumb".substr($pathCompleto, (strlen($pathCompleto) - 4), strlen($pathCompleto));
                    }
                    echo $gestorFormRow->render($form->get('foto'));
                    ?>
                    <label class="col-sm-2&#x20;control-label" for="foto"></label>
                    <div class='col-sm-10'>
                        <?php
                        echo ("<img src='".$pathCompleto."'>");
                        ?>
                    </div>


                </div>
                <div class="box-footer">
                    <?php
                    $submitButton = $form->get('submit');
                    echo $this->formHidden($form->get('id'));
                    echo $this->formHidden($form->get('fecha_creacion'));
                    echo $this->formSubmit($submitButton);
                    ?>
                </div>
                <?php echo $this->form()->closeTag();?>
            </div>
        </div>
    </div>
</div>