<?php
$title = 'Sustitución de especialista';

$foto = '/upload/especialista/' . $especialistaEditar->foto;

$foto = preg_replace("/(.*)\.(png|gif|jpg|jpeg)$/", "$1_thumb.$2", $foto);

$form = $this->form;

$form->prepare();

$gestorFormRow = $this->gestor_form_row();
?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <?php if(count($equiposEspecialista)):

                echo $this->form()->openTag($form); ?>

                <div class="box-body">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="box text-center js-ficha-especialista">
                                <div class="box-header with-border">
                                    <strong><?=$especialistaEditar->nombre . ' ' . $especialistaEditar->apellido1 . ' ' . $especialistaEditar->apellido2;?></strong>
                                </div>
                                <div class="box-body">
                                    <img class="img-responsive pull-center" src="<?=$foto?>" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <?php
                    $countEquiposPorDirector = count($equiposEspecialista);
                    foreach ($equiposEspecialista as $idDirector => $equipos) :?>
                        <div class='form-group'>
                            <?php $url = $this->url('mastah/sections', array('section' => 'director_relacion', 'action' => 'equipos', 'id' => $idDirector)); ?>
                            <div class="col-sm-2">
                                <div class="row">
                                    <h5 class="col-sm-12"><strong><?=$equipos['director']?></strong></h5>
                                    <h5 class="col-sm-12"><a class="btn btn-info btn-flat btn-xs" href='<?=$url?>' target='_blank'>Ver equipos</a></h5>
                                </div>
                            </div>
                            <div class='col-sm-10'>
                                <?php
                                $countEquipos = count($equipos['equipos']);
                                foreach ($equipos['equipos'] as $equipo) :?>
                                    <div class="form-group js-especialista">
                                        <div class="col-sm-3 js-foto-especialista">
                                            <!--<img class="img-responsive pull-right" src="<?/*=$foto*/?>" width="100" />-->
                                        </div>
                                        <div class="col-sm-9">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <h5>Equipo <?=$equipo['id']?></h5>
                                                </div>
                                                <div class="col-sm-12">
                                                    <div class="row">
                                                        <div class="col-sm-6 col-xs-12">
                                                            <?php
                                                            // En vez de dejar que nos lo renderice él lo vamos a hacer nosotros para poder meterle el link a los equipos del DR
                                                            $select = $form->get('idespecialista_'.$equipo['id']);
                                                            echo $this->formSelect($select); ?>
                                                        </div>
                                                        <div class="col-sm-5 col-xs-12">
                                                            <?php if($countEquipos > 1 or $countEquiposPorDirector > 1):?>
                                                                <a class="btn btn-warning js-sustituir-especialista" data-rel="<?=$equipo['id']?>">Aplicar al resto de equipos</a>
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach;?>
                            </div>
                        </div>
                        <hr>
                    <?php endforeach; ?>
                </div>

                <div class="box-footer">
                    <?php
                    $submitButton = $form->get('submit');
                    echo $this->formHidden($form->get('id'));
                    echo $this->formSubmit($submitButton);
                    ?>
                </div>
                <?php echo $this->form()->closeTag();
            else:?>
                <div class="box-body">
                    El especialista  no tiene ningún equipo asignado
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>