<?php

$title = 'Add user';
$this->headTitle($title);

$form = $this->form;

$gestorFormRow = $this->gestor_form_row();

$form->prepare();
?>
<div class="row">
    <?php if(count($messages)):?>
        <div class="col-md-12">
            <div class="alert alert-warning alert-dismissable">
                <?php foreach ($messages as $message) :?>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                    <h4><i class="icon fa fa-warning"></i> Alert!</h4>
                    <?= $message; ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif;?>
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <?php echo $this->form()->openTag($form);?>
            <div class="box-body">
                <?php
                echo $gestorFormRow->render($form->get('login'));
                echo $gestorFormRow->render($form->get('idPerfil'));
                echo $gestorFormRow->render($form->get('password'));
                echo $gestorFormRow->render($form->get('password2'));
                ?>
            </div>
            <div class="box-footer">
                <?php echo $this->formHidden($form->get('id'));?>
                <?php
                $submitButton = $form->get('submit');
                echo $this->formSubmit($submitButton);?>
            </div>
            <?php echo $this->form()->closeTag();?>
        </div>
    </div>
</div>