<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ABS Consultor')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.jpg'))
                        ->prependStylesheet($this->basePath('absconsultor/css/absconsultor.css'))
                        ->prependStylesheet($this->basePath('absconsultor/vendor/bxslider/jquery.bxslider.css'))
                        ->prependStylesheet($this->basePath('absconsultor/vendor/owl-carousel/owl.theme.css'))
                        ->prependStylesheet($this->basePath('absconsultor/vendor/owl-carousel/owl.carousel.css'))
                        ->prependStylesheet($this->basePath('absconsultor/vendor/bootstrap/css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('absconsultor/vendor/bootstrap/css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('absconsultor/vendor/font-awesome/css/font-awesome.min.css'))
                        ->prependStylesheet('https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700|Open+Sans')
        ?>

    </head>
    <body>
        <nav class="navbar navbar-fixed-top transition" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img width="120" src="<?php echo $this->basePath('img/white-logo.png') ?>" alt="Logo ABS Consultor"/>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <!--<li class="active"><a href="<?php /*echo $this->url('home') */?>"><?php /*echo $this->translate('Home') */?></a></li>-->
                        <li><a href="/empresa">Empresa</a></li>
                        <li><a href="/trabajos">Trabajos</a></li>
                        <li><a href="/blog">Blog</a></li>
                        <li><a href="/contacto">Contacto</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container-fluid abs">

            <?php echo $this->content; ?>

        </div> <!-- /container -->

        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <a href="<?php echo $this->url('home') ?>" class="brand-logo">
                            <img width="150" src="<?php echo $this->basePath('img/white-logo.png') ?>" alt="Logo ABS Consultor" />
                        </a>
                    </div>

                    <div class="col-md-4">
                        <ul class="nav navbar-nav footer-nav">
                            <!--<li class="active"><a href="<?php /*echo $this->url('home') */?>"><?php /*echo $this->translate('Home') */?></a></li>-->
                            <li><a href="/empresa">Empresa</a></li>
                            <li><a href="/trabajos">Trabajos</a></li>
                            <li><a href="/blog">Blog</a></li>
                            <li><a href="/contacto">Contacto</a></li>
                        </ul>
                    </div>

                    <div class="col-md-4 text-right contact-info">
                        <div class="row">
                            <div class="col-md-12">
                                <p>Síguenos en</p>
                                <div class="contact-icons">
                                    <a href="http://www.twitter.com" target="_blank"><i class="fa fa-twitter"></i></a>
                                    <a href="http://www.facebook.com" target="_blank"><i class="fa fa-facebook-official"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p>Contáctanos</p>
                                <div class="contact-icons">
                                    <a class="phone" href="tel:949335808">659 666 888 <i class="social-icon fa fa-phone"></i></a>
                                    <a class="mail" href="mailto:info@absconsultor.es">info@absconsultor.es <i class="social-icon fa fa-envelope"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8">
                        <a href="">Aviso Legal</a>&nbsp;&nbsp;&nbsp;<a href="">Política de privacidad</a>
                    </div>
                </div>
            </div>

        </footer>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath('absconsultor/vendor/jquery/jquery.min.js'))
            ->appendFile($this->basePath('absconsultor/vendor/bootstrap/js/bootstrap.min.js'))
            ->appendFile($this->basePath('absconsultor/vendor/owl-carousel/owl.carousel.min.js'))
            ->appendFile($this->basePath('absconsultor/vendor/bxslider/plugins/jquery.fitvids.js'))
            ->appendFile($this->basePath('absconsultor/vendor/bxslider/plugins/jquery.easing.1.3.js'))
            ->appendFile($this->basePath('absconsultor/vendor/bxslider/jquery.bxslider.min.js'))
            ->appendFile($this->basePath('absconsultor/dist/dist.js'))

        ; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
