<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete perfil';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete profile
    '<?php echo $this->escapeHtml($perfil->nombre); ?>' with description
    '<?php echo $this->escapeHtml($perfil->descripcion); ?>'?
</p>
<?php
$url = $this->url('mastah/sections', array(
    'section' => 'perfil',
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $perfil->id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>