<?php

$title = 'Edit profile';
$this->headTitle($title);

$form = $this->form;

$gestorFormRow = $this->administrator_form_row();

$form->prepare();
?>

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <?php echo $this->form()->openTag($form);?>
            <div class="box-body">
                <?php
                echo $gestorFormRow->render($form->get('nombre'));
                echo $gestorFormRow->render($form->get('descripcion'));
                echo $gestorFormRow->render($form->get('gestorPerfilIdPadre'));
                ?>
                <!--<div class="form-group">
                    <label class="col-sm-2 control-label">Perfil Padre</label>
                    <div class="col-sm-10">
                        <?php /*$select = $form->get('idPerfilPadre');*/?>
                        <select name="idPerfilPadre" class="form-control">

                            <?php /*if ($hayRaiz == 1)
                            {
                                //<option value="">[perfil raiz]</option>
                                echo ('<option value="">[perfil raiz]</option>');
                            }

                             foreach ($perfilList as $elemento):
                                $selected = $elemento['id'] == $select->getValue() ? "selected='selected'" : "";

                                if ($elemento['esAdmin'] != 1) {
                                    */?>
                                    <option value="<?/*= $elemento['id'] */?>" <?/*= $selected; */?>><?/*= $elemento['nombre'] */?></option>
                                    <?php
/*                                }


                             endforeach;*/?>
                        </select>
                    </div>
                </div>-->
            </div>
            <div class="box-footer">
                <?php
                $submitButton = $form->get('submit');
                echo $this->formHidden($form->get('id'));
                echo $this->formSubmit($submitButton);
                ?>
            </div>
            <?php echo $this->form()->closeTag();?>
        </div>
    </div>
</div>