<?php

$title = 'Guía de Uso';
$this->headTitle($title);

$form = $this->form;

$form->prepare();

$gestorFormRow = $this->gestor_form_row();

?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>

            <div class="box-body">

            <?php

                // Comprobamos si existe el fichero de GuiaDeUso.pdf
                if (file_exists($pathUpload.$nombreFichero))
                {
                    echo ("<a href='upload/".$path_guia.$nombreFichero."' target='_blank'>");
                    echo ("<i class='fa fa-fw fa-file-pdf-o' style='font-size:26px;'></i> Descargar Guía de Uso (PDF)");
                    echo ("</a>");
                } else {
                    echo ("No existe una Guía de Uso actualmente.");
                }
                echo ("<br/><br/>");
                if (($errorUpload != null) && ($errorUpload != ''))
                {
                    echo ("<p style='color: #ff0000;'>".$errorUpload."</p>");
                } else {
                    if (($uploadCorrecto != null) && ($uploadCorrecto != ''))
                    {
                        echo ("<p style='color: #00aa00;'>".$uploadCorrecto."</p>");
                    }
                    echo ("<p>Suba de nuevo un fichero PDF para sobreescribir la guía.");
                }


            ?>

                <div class="box-footer">

                    <?php
                    echo $this->form()->openTag($form);
                    echo $this->formFile($form->get('pdf'));

                    ?>
                    <br/><br/>
                    <?php
                    $submitButton = $form->get('submit');
                    echo $this->formSubmit($submitButton);
                    ?>


                </div>

            </div>

        </div>
    </div>
</div>

