<?php
$title = 'Generar presentación 1+9';

?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>


            <div class="box-body">
                <div class="callout callout-danger">
                    <h4>
                        No puedes generar presentaciones.
                    </h4>
                    <br/>
                    <p>
                        No pueden generarse presentaciones con este tipo de usuario.
                    </p>
                </div>
            </div>


</div>
        </div>
    </div>