<?php

$title = 'Generar presentación 1+9';

$form = $this->form;

// Vamos a hacer que vaya a otra accion
$form->setAttribute('action', $this->url('mastah/sections', array('section' => 'presentacion', 'action' => 'create')));

$form->prepare();

$gestorFormRow = $this->gestor_form_row();

$this->headTitle($title);

?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>

            <div class="box-body">
                <?php

                // Vamos a pintar el formulario
                echo $this->form()->openTag($form);

                // ------------------------- ZONA 1 -------------------------
                // Metemos a mano el input del nombre de la empresa
                echo $gestorFormRow->render($form->get('nombre_empresa'));

                // ------------------------- ZONA 2 -------------------------
                // Sacamos todos los equipos de este director
                ?>
                <div class='form-group'>
                    <label class="col-sm-2 control-label">Elija un equipo</label>
                    <div class='col-sm-10'>

                    <?php
                    // Recorremos los equipos que tenemos
                    for ($i = 0; $i < $cuantosEquipos; $i++):
                        // Ahora por cada uno una collapsed box
                        ?>
                        <div class="box box-default collapsed-box">
                            <div class="box-header with-border">
                                <h3 class="box-title">
                                    <input
                                        type="radio"
                                        name="idequipo"
                                        value="<?= $arrayEquipos[$i]['id'];?>"
                                        <?= $i == 0 ? "checked='checked'" : "" ?>
                                        />
                                    Equipo <?=($i+1); ?></h3>
                                <div class="box-tools pull-right">
                                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                                </div><!-- /.box-tools -->
                            </div><!-- /.box-header -->

                            <div class="box-body">

                            <!-- Equipo en sí -->
                            <?php
                            // Para cada uno vamos a pintar sus datos
                            foreach ($arrayNombresEspecialidad as  $n => $especialidad) :
                                if ((($n-1) % 3) == 0):?>
                                <div class='row'>
                                <?php endif;?>

                                <div class='col-sm-4 col-xs-4'>
                                    <div class="box box-default">
                                        <div class="box-header text-center with-border">
                                            <small><strong><?=ucfirst($especialidad['nombreInterno'])?></strong></small>
                                        </div>
                                        <div class="box-body">
                                            <?php
                                            // Sacamos / pintamos los datos del especialista
                                            $idEspecialidad = $especialidad['id'];
                                            $fotoTemp = $arrayEquipos[$i][$n]['foto'];
                                            $nombre = $arrayEquipos[$i][$n]['nombre']." ".$arrayEquipos[$i][$n]['apellido1']." ".$arrayEquipos[$i][$n]['apellido2'];
                                            ?>
                                            <div class="row">
                                                <div class="col-lg-5 col-md-12">
                                                    <h6><?=$nombre;?></h6>
                                                </div>
                                                <div class="col-lg-7 col-md-12">
                                                    <?php
                                                    // Metemos la imagen para que se vea que existe
                                                    $path = '/upload/especialista/';
                                                    $pathCompleto = $path . $fotoTemp;
                                                    // Sacamos el thumb que es el que queremos montar
                                                    $pathCompleto = substr($pathCompleto, 0, strlen($pathCompleto) - 4) . "_thumb" . substr($pathCompleto, (strlen($pathCompleto) - 4), strlen($pathCompleto));
                                                    ?>
                                                    <img class="img-responsive" src='<?=$pathCompleto?>'/>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <?php if (($n % 3) == 0):?>
                                </div>
                                <?php endif;
                            endforeach;?>

                            <!-- CERRAMOS The body of the box -->
                            </div><!-- /.box-body -->
                        </div><!-- /.box -->
                        <?php endfor; ?>
                        <!-- Cerramos bloque derecho del form -->
                    </div>
                </div>
                <?php
                // ------------------------- ZONA 3 -------------------------
                // Página de oficina
                ?>

                <div class="form-group">
                    <label class="col-sm-2 control-label">¿Generar página de oficina?</label>
                    <div class="col-md-10">
                        <div class="radio">
                            <label>
                                <input type="radio" name="generaroficina" id="sioficina" value="1" checked>
                                Sí
                            </label>
                        </div>

                        <div class="radio">
                            <label>
                                <input type="radio" name="generaroficina" id="nooficina" value="0">
                                No
                            </label>
                        </div>
                    </div>
                </div>

                <div class="box box-default js-pagina-oficina">
                    <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs pull-right">
                            <li><a href="#tab_otros_contactos" data-toggle="tab">Otros Contactos</a></li>
                            <li><a href="#tab_gestion_administrativa" data-toggle="tab">Gestión Administrativa</a></li>
                            <li><a href="#tab_gestion_comercial" data-toggle="tab">Gestión Comercial</a></li>
                            <li><a href="#tab_gestor" data-toggle="tab">Gestor</a></li>
                            <li class="active"><a href="#tab_director" data-toggle="tab">Director</a></li>
                            <li class="pull-left header">Página oficina</li>
                        </ul>
                        <div class="tab-content">
                            <?php
                            $campos = array(
                                'nombre'    => 'Nombre',
                                'telefono'  => 'Teléfono',
                                'email'     => 'Correo Electrónico'
                            );
                            ?>
                            <div class="tab-pane active" id="tab_director">
                                <div class="box-header with-border js-director">
                                    <?php
                                    echo $gestorFormRow->render($form->get('do_nombre'));
                                    echo $gestorFormRow->render($form->get('do_telefono'));
                                    echo $gestorFormRow->render($form->get('do_email'));
                                    ?>
                                </div>
                            </div><!-- /.tab-pane -->
                            <div class="tab-pane" id="tab_gestor">
                                <div class="box-header with-border js-gestor">
                                    <?php
                                    echo $gestorFormRow->render($form->get('ge_nombre'));
                                    echo $gestorFormRow->render($form->get('ge_telefono'));
                                    echo $gestorFormRow->render($form->get('ge_email'));
                                    ?>
                                </div>
                            </div><!-- /.tab-pane -->
                            <div class="tab-pane" id="tab_gestion_comercial">
                                <div class="box-header with-border js-gestion-comercial">
                                    <div>
                                        <?php

                                        $gcJson = is_object($ultimosDatos) ? json_decode($ultimosDatos->gcJson) : array();
                                        $maxGc = 4;
                                        $counter = count($gcJson);

                                        foreach($gcJson as $g => $gc):?>

                                            <div class="form-block">

                                                <?php foreach($campos as $nombreCampo => $labelCampo):?>

                                                    <div class='form-group'>
                                                        <label class="col-sm-2 control-label"><?=$labelCampo;?></label>
                                                        <div class='col-sm-10'>
                                                            <input type="text"
                                                                   name="gc_<?=$nombreCampo; ?>_<?=$g; ?>"
                                                                   id="gc_<?=$nombreCampo; ?>_<?=$g; ?>"
                                                                   class="form-control"
                                                                   value="<?=$gc->{$nombreCampo}?>">
                                                        </div>
                                                    </div>

                                                <?php endforeach;?>

                                                <div class="form-group">
                                                    <label class="col-sm-2 control-label">&nbsp</label>
                                                    <div class="col-sm-10">
                                                        <button class="btn btn-xs gc btn-danger js-remove">Eliminar</button>
                                                    </div>
                                                </div>

                                            </div>
                                        <?php endforeach ;?>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-12">
                                            <button data-counter="<?=$counter;?>"
                                               data-max-counter="<?=$maxGc?>"
                                               class="btn btn-primary btn-xs gc js-add <?=$counter == $maxGc ? 'hide' : ''?>">
                                                Añadir Gestor Comercial
                                            </button>
                                        </div>
                                    </div>

                                </div>
                            </div><!-- /.tab-pane -->
                            <div class="tab-pane" id="tab_gestion_administrativa">
                                <div class="box-header with-border js-gestion-administrativa">

                                    <div>

                                        <?php
                                        $gaJson = is_object($ultimosDatos) ? json_decode($ultimosDatos->gaJson) : array();
                                        $counter = count($gaJson);
                                        $maxGa = 4;

                                        foreach($gaJson as $g => $ga):?>

                                            <div class="form-block">

                                                <?php foreach($campos as $nombreCampo => $labelCampo):?>

                                                    <div class='form-group'>
                                                        <label class="col-sm-2 control-label"><?=$labelCampo;?></label>
                                                        <div class='col-sm-10'>
                                                            <input type="text"
                                                                   name="ga_<?=$nombreCampo; ?>_<?=$g; ?>"
                                                                   id="ga_<?=$nombreCampo; ?>_<?=$g; ?>"
                                                                   class="form-control"
                                                                   value="<?=$ga->{$nombreCampo}?>">
                                                        </div>
                                                    </div>
                                                <?php endforeach;?>

                                                <div class="form-group">
                                                    <label class="col-sm-2 control-label">&nbsp</label>
                                                    <div class="col-sm-10">
                                                        <button class="btn btn-xs ga btn-danger js-remove">Eliminar</button>
                                                    </div>
                                                </div>

                                            </div>

                                        <?php endforeach ;?>

                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-12">
                                            <button data-counter="<?=$counter;?>"
                                               data-max-counter="<?=$maxGa?>"
                                               class="btn btn-xs btn-primary js-add ga <?=$counter == $maxGa ? 'hide' : ''?>">
                                                Añadir Gestor Administrativo
                                            </button>
                                        </div>
                                    </div>

                                </div>
                            </div><!-- /.tab-pane -->
                            <div class="tab-pane" id="tab_otros_contactos">
                                <div class="box-header with-border js-otros-contactos">
                                    <div>
                                        <?php

                                        $otJson = is_object($ultimosDatos) ? json_decode($ultimosDatos->otJson) : array();
                                        $maxOt = 4;
                                        $counter = count($otJson);

                                        foreach($otJson as $g => $ot):?>

                                            <div class="form-block">

                                                <?php foreach($campos as $nombreCampo => $labelCampo):?>
                                                    <div class='form-group'>
                                                        <label class="col-sm-2 control-label"><?=$labelCampo;?></label>
                                                        <div class='col-sm-10'>
                                                            <input type="text"
                                                                   name="ot_<?=$nombreCampo; ?>_<?=$g; ?>"
                                                                   id="ot_<?=$nombreCampo; ?>_<?=$g; ?>"
                                                                   class="form-control"
                                                                   value="<?=$ot->{$nombreCampo}?>">
                                                        </div>
                                                    </div>
                                                <?php endforeach;?>

                                                <div class="form-group">
                                                    <label class="col-sm-2 control-label">&nbsp</label>
                                                    <div class="col-sm-10">
                                                        <button class="btn btn-xs ot btn-danger js-remove">Eliminar</button>
                                                    </div>
                                                </div>

                                            </div>
                                        <?php endforeach ;?>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-12">
                                            <button data-counter="<?=$counter;?>"
                                               data-max-counter="<?=$maxOt?>"
                                               class="btn btn-primary btn-xs js-add ot <?=$counter == $maxOt ? 'hide' : ''?>">
                                                Añadir Otro Contacto
                                            </button>
                                        </div>
                                    </div>

                                </div>
                            </div><!-- /.tab-pane -->
                        </div><!-- /.tab-content -->
                    </div><!-- nav-tabs-custom -->
                </div>


                <div class="form-group">
                    <label class="col-sm-2 control-label">Idiomas a generar</label>
                    <div class="col-sm-10">
                        <?php foreach ($arrayLenguajes as $ll => $lenguaje):?>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox"
                                        <?=($ll == 0 ? "checked = 'checked'" : "")?>
                                           class="js-lenguaje"
                                           name="idlenguaje"
                                           value="<?=$lenguaje['id']?>"
                                        />
                                    <?=$lenguaje['nombreInterno'];?>
                                </label>
                            </div>
                            <iframe class="hide" id="link_lang_<?=$lenguaje['id'];?>" src=""></iframe>
                        <?php endforeach; ?>
                    </div>
                </div>
                <?php
                // ------------------------- ZONA 4 -------------------------
                // Selección de idiomas
                ?>

                <div class="box-footer">
                    <div class="box-header with-border">
                        <div class="col-sm-10">
                            <div class='form-group'>
                                <label class="col-sm-2 control-label">
                                    <input type="submit" name="submit" id="submitbutton" class="btn btn-primary" value="Crear PDFs">
                                </label>
                            </div>
                        </div>
                    </div>
                </div>

                <?php echo $this->form()->closeTag(); ?>

            </div>
        </div>
    </div>
</div>