<?php

$title = 'Permisos';
$this->headTitle($title);


?>

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>


            <div class="box-body">
                <?php if ($this->flashMessenger()->hasMessages()) :
                    $messages = $this->flashMessenger()->getMessages();
                    foreach ($messages as $msg): ?>
                        <div class='mensaje_gestor'><?php echo $msg?></div>
                    <?php endforeach; ?>
                <?php endif; ?>


                <select id="idPerfil" name="idPerfil">
                <?php

                echo ("<option value=''>[Elige un perfil]</option>");
                // Vamos a montar un combo con ajax
                foreach ($perfiles as $elemento)
                {
                    echo ("<option value='".$elemento->id."'>".$elemento->nombre."</option>");
                }
                ?></select>

                <div id="div_permisos" style="display: none;">

                    <br/>
                    <strong>Acceso a entradas de menú</strong>
                    <br/><br/>
                    <form method="post" action="permisos/write">
                        <table class='table' style='width: 600px'>
                            <thead>
                            <tr>
                                <th>Controlador</th>
                                <th>¿Puede acceder?</th>
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </form>
                </div>

            </div>

        </div>
    </div>
</div>

<?php
//esta sería la forma de añadir un js en la vista y que zend nos lo pinte al final del layout
// (justo donde hagamos el echo de $this->inlineScript(), que normalmente será después de todos los
// archivos .js). De esta forma, no es necesario obligar al usuario a cargar los js en el head,
// ya que lo ideal y recomendado (salvo ciertas excepciones) es cargarlos justo antes de la etiqueta
// de cierre del body.

$this->inlineScript()->captureStart();
echo <<<JS
$("#idPerfil").change(function  () {
    $.ajax({
        type: "post",
        data: ({
            idPerfil : $('#idPerfil').find('option:selected').val()
        }),
        url: "permisos/list",
        success: function(data){
        var divPermisos = $("#div_permisos");
         divPermisos
            .css('display','block')
            .find('table tbody')
                .html(data)
        }
    });
});
JS;
$this->inlineScript()->captureEnd();
?>