<?php

$title = 'List users';
$this->headTitle($title);

?>

<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
                <a class="pull-right" href="<?php echo $this->url('mastah/sections', array('section' => 'gestorusuarios','action'=>'add'));?>">Add new user</a>
            </div>
            <div class="box-body">

                <?php if ((isset($usuarios)) && (count($usuarios) > 0)) :?>

                <table class="table table-bordered table-hover">
                    <tr>
                        <th>Nombre</th>
                        <th>Fecha de alta</th>
                        <th>Último login</th>
                        <th>Perfil</th>
                        <th class="text-center">Editar</th>
                        <th class="text-center">Eliminar</th>
                    </tr>

                    <?php foreach ($usuarios as $elemento) :?>

                    <tr>
                        <td><?php
                            if ($quienSoy == $elemento->login)
                            {
                                echo ("<span class='tabla-destaca'>");
                                echo $elemento->login;
                                echo ("</span>");
                            } else {
                                echo $elemento->login;
                            }

                            ?>
                        </td>
                        <td><?php echo $elemento->fechaAlta;?></td>
                        <td><?php echo $elemento->ultimoLogin;?></td>
                        <td><?php echo $elemento->nombre;?></td>
                        <td class="text-center">

                            <?php
                            $href = $this->url('mastah/sections', array(
                                'section' => 'gestorusuarios',
                                'action' => 'edit',
                                'id' => $elemento->id
                            ));
                            ?>

                            <a href="<?php echo $href?>"><i class="fa fa-edit"></i> </a>
                        </td>

                        <?php if ($elemento->id != 1) :?>

                            <td class="text-center">
                                <?php
                                $href = $this->url('mastah/sections', array(
                                    'section' => 'gestorusuarios',
                                    'action' => 'delete',
                                    'id' => $elemento->id
                                ));
                                ?>
                                <a href="<?php echo $href;?>"
                                   class="delete_alert"
                                   texto="Are you sure you want to delete user '<?=$elemento->login?>'"
                                    ><i class="fa fa-remove"></i></a>
                            </td>

                        <?php else: ?>
                            <td class="text-center"><i class="fa fa-ban"></i></td>
                        <?php endif; ?>
                    </tr>
                    <?php endforeach;?>
                </table>
            <?php endif; ?>
            </div>
        </div>
    </div>
</div>