<?php

if (($error != null) && ($error != ''))
{
    echo ("<span style='color: red;'>");
    echo ("ERROR EN LA IMPORTACION DE FOTOS : ".$error);
    echo ("</span>");
}

if ($exito == 'si')
{
    echo ("<span style='color: green;'>");
    echo ("La importación de fotos se ha realizado con éxito. Se procesaron ".$numLineas." líneas.");
    echo ("</span>");

    echo ("<br/><br/><br/>");
    echo ("<span style='color: red;'>");
    echo ($errores);
    echo ("</span>");


}