<?php

$title = 'Edición de un coordinador';


?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>

                <div class="box-body">
                    <form action="&#x2F;coordinador&#x2F;edit&#x2F;<?php echo $arrayCoordinador['id']; ?>" method="POST" class="form-horizontal" name="Gestor_Form" id="Gestor_Form">

                    <div class='form-group'>
                        <label class="col-sm-2&#x20;control-label" for="idcargo">Último acceso</label>
                        <div class='col-sm-10' style='vertical-align: bottom;'>
                            <input type="text" value="<?php echo $arrayCoordinador['ultimoLogin']; ?>" class="form-control" readonly>
                        </div>
                    </div>


                        <div class='form-group'>
                            <label class="col-sm-2&#x20;control-label" for="idcargo">Usuario (login)</label>
                            <div class='col-sm-10' style='vertical-align: bottom;'>
                                <input type="text" value="<?php echo $arrayCoordinador['login']; ?>" class="form-control" id="login" name="login">
                            </div>
                        </div>

                        <div class='form-group'>
                            <label class="col-sm-2&#x20;control-label" for="idcargo">Correo electrónico</label>
                            <div class='col-sm-10' style='vertical-align: bottom;'>
                                <input type="text" value="<?php echo $arrayCoordinador['email']; ?>" class="form-control" id="email" name="email">
                            </div>
                        </div>


                    <div class="box-footer">
                        <input type="submit" class="btn&#x20;btn-primary" value="Grabar">
                    </div>

                    </form>


                </div>

            </div>








        </div>
    </div>
</div>