<?php

$title = 'Listado de coordinadores';
$this->headTitle($title);

?>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $this->escapeHtml($title); ?></h3>
                <a class="pull-right" href="<?php echo $this->url('mastah/sections', array('section' => 'coordinador','action'=>'add'));?>">Nuevo</a>
            </div>

            <div class="box-body">


                <table class="table table-bordered table-hover">
                    <tr>
                        <th>Usuario</th>
                        <th>Email</th>
                        <th>Último acceso</th>
                        <th>Editar</th>
                        <th>Activar / Desactivar</th>
                    </tr>
                    <?php
                    foreach ($arrayCoordinadores as  $i => $entrada) {
                        echo ("<tr>");

                        echo ("<td>");
                        echo ($entrada->login);
                        echo ("</td>");

                        echo ("<td>");
                        echo ($entrada->email);
                        echo ("</td>");

                        echo ("<td>");
                        echo ($entrada->ultimoLogin);
                        echo ("</td>");

                        // Editar y activar/desactivar
                        ?>
                        <td class="text-center">
                            <?php
                            $href = $this->url('mastah/sections', array(
                                'section' => 'coordinador',
                                'action' => 'edit',
                                'id' => $entrada->id
                            ));
                            ?>
                            <a href="<?php echo $href?>"><i class="fa fa-edit fuentegrande"></i> </a>
                        </td>

                        <td class="text-center">
                            <?php
                            if ($entrada->activo == 1)
                            {
                                $href = $this->url('mastah/sections', array(
                                    'section' => 'coordinador',
                                    'action' => 'desactivar',
                                    'id' => $entrada->id
                                ));

                                echo ("<a href='".$href."'>");
                                echo ("Desactivar");
                            } else {
                                $href = $this->url('mastah/sections', array(
                                    'section' => 'coordinador',
                                    'action' => 'activar',
                                    'id' => $entrada->id
                                ));
                                echo ("<a href='".$href."'>");
                                echo ("Activar");
                            }
                            echo ("</a>");
                            ?>
                        </td>
                        <?php

                        echo ("</tr>");
                    }
                    ?>
                </table>

            </div>
        </div>
    </div>
</div>