<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?=$title;?></h3>
            </div>
            <div class="box-body">
                <div id="uploader"></div>
                <input type="hidden" id="media_module_target" value="<?=$moduleTarget?>" />
                <input type="hidden" id="media_module_id" value="<?=$id?>" />
            </div>
        </div>
    </div>
</div>