<?php

namespace AmLogin;

/**
 * Generated by ZF2ModuleCreator
 */

return [
    'view_manager' => [
        'template_path_stack' => [
            __DIR__ . '/../view',
        ],
    ],

    'controllers' => [],

    'service_manager' => [
    ],

    'router' => [
    ]
];
