<?php

/**
 * Generated by ZF2ModuleCreator
 */

namespace Administrator;

use Administrator\View\Helper\AdministratorFormRow;
use Zend\ModuleManager\Feature\AutoloaderProviderInterface;
use Zend\ModuleManager\Feature\ConfigProviderInterface;

use Zend\ModuleManager\ModuleEvent;
use Zend\ModuleManager\ModuleManager;
use Zend\Mvc\MvcEvent;
use Zend\Validator\AbstractValidator;

class Module implements AutoloaderProviderInterface, ConfigProviderInterface
{
    protected $mvcEvent;

    /**
     * Returns configuration to merge with application configuration
     *
     * @return array|\Traversable
     */
    public function getConfig()
    {
        return include __DIR__ . '/config/module.config.php';
    }

    /**
     * Return an array for passing to Zend\Loader\AutoloaderFactory.
     *
     * @return array
     */
    public function getAutoloaderConfig()
    {
        return array(
            'Zend\Loader\StandardAutoloader' => array(
                'namespaces' => array(
                    // Autoload all classes from namespace 'Administrator' from '/module/Administrator/src/Administrator'
                    __NAMESPACE__ => __DIR__ . '/src/' . __NAMESPACE__,
                )
            )
        );
    }

    public function getControllerConfig()
    {
        return array(
            'factories' => array(
                'Administrator\Factory\AdminControllerFactory' => 'Administrator\Factory\AdminControllerFactory',
            ),
            'invokables' => array(

            )
        );
    }

    public function getServiceConfig()
    {
        return array(
            'initializers' => array(
                'Administrator\Initializer\DatabaseInitializer',
            ),
            'abstract_factories' => array(
                'Administrator\Factory\AdministratorTableAbstractFactory',
                'Administrator\Factory\AdministratorModelAbstractFactory',
                'Administrator\Factory\DatatableConfigAbstractFactory',
            ),
            'factories' => array(

                'AuthService'                                       => 'Administrator\Service\AuthService',
                'Administrator\Service\SessionService'              => 'Administrator\Service\SessionService',
                'Administrator\Service\AdministratorFormService'    => 'Administrator\Service\AdministratorFormService',
                'Administrator\Service\DatatableService'            => 'Administrator\Service\DatatableService',
            ),
            'invokables' => array(
                'Administrator\Model\AuthStorage'                   => 'Administrator\Model\AuthStorage',
            )
        );
    }

    public function getViewHelperConfig()
    {
        return array(
            'invokables' => array(
                'AdministratorMenu' => 'Administrator\View\Helper\AdministratorMenu',
            ),
            'factories' => array(
                'administrator_form_row' => function ($sm) {
                    return new AdministratorFormRow($sm);
                }
            )
        );
    }

   /* EN UN INTENTO DE HACER LA CARGA DE LOS MODULOS QUE PERTENECEN AL ADMINISTRADOR DE FORMA
   INDEPENDIENTE AL RESTO DE LA PLATAFORMA SE HAN CREADO ESTOS DOS MÉTODOS.
   HE CONSEGUIDO ACCEDER A TODA LA INFORMACIÓN NECESARIA PERO ZEND NO ES CAPAZ DE RECONOCER
   LOS MÓDULOS CARGADOS DE DICHA FORMA.
   
    public function init(ModuleManager $moduleManager)
    {
        $eventManager = $moduleManager->getEventManager();
        $eventManager->attach(ModuleEvent::EVENT_LOAD_MODULES_POST,array($this, 'onLoadModule'));
    }

    public function onLoadModule(ModuleEvent $event)
    {
        $serviceManager = $event->getParam('ServiceManager');

        $router = $serviceManager->get('Router');
        $request = $serviceManager->get('Request');

        $routeMatch = $router->match($request);

        if ($routeMatch->getParam('controller') == 'Administrator\Factory\AdminControllerFactory') {
            $moduleManager = $serviceManager->get('ModuleManager');
        }
    }*/

    public function onBootstrap(MvcEvent $e)
    {
        $this->mvcEvent = $e;

        $this->loadTranslations();
    }

    private function loadTranslations()
    {
        $serviceManager = $this->mvcEvent->getApplication()->getServiceManager();
        $translator = $serviceManager->get('translator');

        $locale = $translator->getLocale();

        $translateFilePath = __DIR__."/language/$locale/";
        $tranlationFiles = array(
            "Zend_Validate",
            "locale",
        );

        foreach ($tranlationFiles as $file) {
            $translateFile = $translateFilePath . "$file.php";
            $translateFile = str_replace('/',DIRECTORY_SEPARATOR,$translateFile);
            $translator->getTranslator()->addTranslationFile(
                'phpArray',
                $translateFile,
                'default',
                $locale);
        }


        AbstractValidator::setDefaultTranslator($translator);
    }
}