<?php

/**
 * Generated by ZF2ModuleCreator
 */

namespace Administrator;

use Administrator\View\Helper\AdministratorFormRow;
use Zend\Authentication\AuthenticationService;
use Zend\ModuleManager\Feature\AutoloaderProviderInterface;
use Zend\ModuleManager\Feature\ConfigProviderInterface;

use Zend\Authentication\Adapter\DbTable\CredentialTreatmentAdapter as AuthAdapter;
use Zend\Mvc\MvcEvent;
use Zend\Validator\AbstractValidator;

class Module implements AutoloaderProviderInterface, ConfigProviderInterface
{

    /**
     * Returns configuration to merge with application configuration
     *
     * @return array|\Traversable
     */
    public function getConfig()
    {
        return include __DIR__ . '/config/module.config.php';
    }

    /**
     * Return an array for passing to Zend\Loader\AutoloaderFactory.
     *
     * @return array
     */
    public function getAutoloaderConfig()
    {
        return array(
            'Zend\Loader\StandardAutoloader' => array(
                'namespaces' => array(
                    // Autoload all classes from namespace 'Administrator' from '/module/Administrator/src/Administrator'
                    __NAMESPACE__ => __DIR__ . '/src/' . __NAMESPACE__,
                )
            )
        );
    }

    public function getControllerConfig()
    {
        return array(
            'factories' => array(
                'Administrator\Factory\AdminControllerFactory' => 'Administrator\Factory\AdminControllerFactory',
            ),
            'invokables' => array(

            )
        );
    }

    public function getServiceConfig()
    {
        return array(
            'initializers' => array(function ($instance, $sm) {
                //Seteamos el dbAdapter para todos los modelos)
                if ($instance instanceof \Zend\Db\Adapter\AdapterAwareInterface) {
                    $instance->setServiceLocator($sm);
                    $instance->setDbAdapter($sm->get('Zend\Db\Adapter\Adapter'));
                }
            }),
            'abstract_factories' => array(
                'Administrator\Factory\AdministratorTableAbstractFactory',
                'Administrator\Factory\AdministratorModelAbstractFactory',
            ),
            'factories' => array(

                'Administrator\Model\AuthStorage' => function ($sm) {
                    return new \Administrator\Model\AuthStorage('AdministratorStorage');
                },
                'AuthService'                            => 'Administrator\Service\AuthService',

                'Administrator\Service\SessionServiceInterface' => 'Administrator\Service\SessionService',
                'Administrator\Factory\PermisosCheckerFactory'  => 'Administrator\Factory\PermisosCheckerFactory',
                'Administrator\Service\AdministratorFormService'       => 'Administrator\Service\AdministratorFormService',
                //'Gestor\Service\DatatableService'        => 'Gestor\Service\DatatableService',

            ),
        );
    }

    public function getViewHelperConfig()
    {
        return array(
            'invokables' => array(
                'AdministratorMenu' => 'Administrator\View\Helper\AdministratorMenu',
            ),
            'factories' => array(

                'settings' => function ($sm) {
                    return new \Gestor\View\Helper\AppSettingsHelper();
                },
                'gestor_user' => function($sm) {
                    return new \Gestor\View\Helper\GestorUserHelper($sm);
                },
                'administrator_form_row' => function ($sm) {
                    return new AdministratorFormRow($sm);
                }
            )
        );
    }

    public function onBootstrap(MvcEvent $e)
    {
        $translator = $e->getApplication()->getServiceManager()->get('translator');

        $locale = $translator->getLocale();

        $translateFile = __DIR__."/language/$locale/Zend_Validate.php";
        $translateFile = str_replace('/',DIRECTORY_SEPARATOR,$translateFile);
        $translator->getTranslator()->addTranslationFile(
            'phpArray',
            $translateFile,
            'default',
            $locale);

        AbstractValidator::setDefaultTranslator($translator);
    }
}