<?php
$contact = $menu->rows['contact']->id;

$contactFormHelper = $this->contactFormHelper($formObject);

?>
<div class="row nav-breadcrumb hidden-xs">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?=$this->url($lang)?>">Home</a></li>
            <li class="breadcrumb-item active"><?=$menu->locale->{$lang}[$contact]->name?></li>
        </ol>
    </div>
</div>

<div class="container contact">
    <article>
        <div class="row">
            <div class="col-md-12">
                <h1><?=$menu->locale->{$lang}[$contact]->name?></h1>

                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php $contactFormHelper->render($lang);?>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12 contact-info">
                       <div class="row">
                            <div class="col-md-12">

                                <h4><?=$this->translate('Social Networks','frontend');?></h4>
                                <div class="contact-icons">
                                    <a href="http://www.twitter.com" target="_blank"><i class="fa fa-twitter"></i></a>
                                    <a href="http://www.facebook.com" target="_blank"><i class="fa fa-facebook-official"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="contact-icons">
                                    <h4><?=$this->translate('Form Phone','frontend');?></h4><a class="phone" href="tel:<?=$appData->locale->{$lang}->phone?>"><?=$appData->locale->{$lang}->phone?></a>
                                    <h4>Email</h4><a class="mail" href="mailto:<?=$appData->locale->{$lang}->email?>"><?=$appData->locale->{$lang}->email?></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>
</div>