<?php
$contact = $menu->rows['contact']->id;

$contactFormHelper = $this->contactFormHelper($formObject);

$flashMessenger = $this->flashMessenger();

?>
<div class="row nav-breadcrumb hidden-xs">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?=$this->url($lang)?>">Home</a></li>
            <li class="breadcrumb-item active"><?=$menu->locale->{$lang}[$contact]->name?></li>
        </ol>
    </div>
</div>

<div class="container contact">
    <article>
        <div class="row">
            <div class="col-md-12">
                <h1><?=$menu->locale->{$lang}[$contact]->name?></h1>


                <div class="row intro-section">
                    <div class="col-xs-12">
                        <?=$menu->locale->{$lang}[$contact]->content;?>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <?php

                        if(is_bool($mailSended) and $mailSended === true) {
                            echo sprintf(
                                "<div class='form-success'>%s</div>",
                                $this->translate('Thank you for contacting us','frontend')
                            );
                        } else {
                            $contactFormHelper->render($lang,$legal);
                            if ($mailSended === false) {
                                echo sprintf(
                                    "<div class='form-error'>%s</div>",
                                    sprintf(
                                        $this->translate("An error occured when submitting the form. Try again later or contact us at <a href='mailto:%s'>%s</a>",'frontend'),
                                        $appData->locale->{$lang}->email,
                                        $appData->locale->{$lang}->email
                                    )
                                );
                            }
                        }
                        ?>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12 contact-info">
                       <div class="row">
                            <div class="col-md-12">

                                <h4><?=$this->translate('Social Networks','frontend');?></h4>
                                <div class="contact-icons">
                                    <a href="http://www.twitter.com" target="_blank"><i class="fa fa-twitter"></i></a>
                                    <a href="http://www.facebook.com" target="_blank"><i class="fa fa-facebook-official"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="contact-icons">
                                    <h4><?=$this->translate('Form Phone','frontend');?></h4><a class="phone" href="tel:<?=$appData->locale->{$lang}->phone?>"><?=$appData->locale->{$lang}->phone?></a>
                                    <h4>Email</h4><a class="mail" href="mailto:<?=$appData->locale->{$lang}->email?>"><?=$appData->locale->{$lang}->email?></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>
</div>