<?php if($esPar):?>
    <tr>
<?php endif;?>

<td class="celda <?=(!$esPar ? 'padding-izq' : '');?>">
    <table cellspacing="0" cellpadding="0" width="10cm">
        <tr>
            <td colspan="2">
                <table cellspacing="0" cellpadding="0">
                    <tr>
                        <td class="cabecera-info cabecera-azul-<?=$countRow;?>">
                            <?=$titulo;?>
                        </td>
                        <td>
                            <img
                                class="esquina-cabecera"
                                src="<?=$baseUrl?>/assets_pdf/borde-cabecera-<?=$countRow;?>.gif"
                                />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="borde borde-azul-<?=$countRow;?>">&nbsp;</td>
        </tr>
        <tr>
            <?php
            foreach($datos as $indexDatos => $dato):?>
            <td class="info">
                <?=$dato['nombre'];?><br>
                <?php if(trim($dato['telefono']) != ''):?>
                    <?=$str['pagina_4_telefono'][$langId];?> <?=$dato['telefono']?> <br>
                <?php endif;?>
                <?=$dato['email'];?>
            </td>
            <?php if(($indexDatos + 1) % 2 == 0) :?>
        </tr><tr>
            <?php endif; ?>
            <?php endforeach;?>
        </tr>
    </table>
</td>

<?php if($esPar):?>
    </tr>
<?php endif;?>