<html>
<head>
    <style type="text/css">

        body {
            font-family: "staglight";
            font-size: 10mm;
        }

        .cabecera {
            font-size: 20pt;
            color: #009EE0;
            width: 300mm;
            padding-top: 35mm;
            padding-left: 20.5mm;
            padding-bottom: 10mm;
        }

        .cabecera-1 {
            padding-bottom: 4mm;
        }

        img {
            width: 100%;
        }
        div {
            display: block;
            float: left;
        }

        .wrapper-pagina-1 {
            padding-left: 3cm; padding-top: 8cm; padding-right: 3cm; display: block; width: 26cm;
        }

        .nombre-empresa-principal {
            font-size: 48pt; color: #009EE0;
        }

        .frase-pagina-1 {
            font-size: 30pt; color: #43B9EB;
        }

        .frase-2-pagina-1 {
            color: #005193; font-size: 10pt; padding-top: 3mm; padding-left: 4cm; padding-right:4cm;
        }

        .frase-3-pagina-1 {
            color: #005193; font-size: 10pt; padding-top: 2mm; padding-left: 4cm; padding-right:4cm; font-family: 'bbvawebbook'; font-weight: bold;
        }

        .tabla-equipo-pagina-1 {
            margin-top: 12mm; margin-left: 75mm;
        }

        .cabecera-equipo {
            background: url('<?=$baseUrl?>/assets_pdf/equipo_<?=$langId?>.png'); height: 5mm; width: 82.5mm;
        }

        .equipo-director {
            padding-bottom: 4mm; padding-right: 2mm; border-left:0.35mm solid #025090; height: 20mm; font-size: 9pt; width: 24.5mm; text-align: right; vertical-align: bottom; color: #025090
        }

        .img_1_mas_9 {
            display: block; width:29mm;
        }

        .equipo-especialistas {
            text-align: left; padding-bottom: 4.5mm; width: 25mm; border-right:0.35mm solid #025090; font-size: 9pt; vertical-align: bottom; color: #025090;
        }

        .pie-equipo {
            border:0.35mm solid #025090;
            font-size: 15pt;
            text-align: center;
            color: #025090;
            padding-top: 1mm;
            padding-bottom: 1mm;
            letter-spacing: 0.7mm;
            font-weight: bold;
        }


        /* -- FIN PAGINA 1 -- */


        /* -- PAGINA 2 -- */

        #director_relacion {
            width: 75mm; margin-left: 20mm; padding-top: 10mm;
        }

        #director_relacion .wrapper-background {
            width: 74.5mm;
            height: 99mm;
            background: url('<?=$baseUrl?>/assets_pdf/img_director_relacion.png')
        }

        #director_relacion table {
            margin-top: 4mm;
            margin-left: 4mm;
            color: white;
            border-top: 0.5mm solid white;
            border-left: 0.5mm solid white;
            border-right: 0.5mm solid white;
        }

        #director_relacion table .cargo {
            font-size: 10pt;
            font-family: 'bbvawebbook';
            font-weight: bold;
            border-right: 0.2mm solid white;
            border-bottom: 0.5mm solid white;
            padding: 2mm;
            padding-top: 8mm;
            padding-bottom: 8mm
        }

        #director_relacion table .nombre {
            font-family: 'bbvawebbook';
            font-size: 7pt;
            padding: 2mm;
            text-align: center;
            border-bottom: 0.5mm solid white;
            width: 20mm;
        }

        #director_relacion table .info-contacto {
            border-bottom: 0.5mm solid white;
            font-size: 8pt;
            padding-top: 1mm;
            padding-bottom: 1mm;
            padding-left: 1mm;
        }

        .icono {
            display: inline-block;
            vertical-align: middle;
            width: 6mm;
            height: 6mm;
            margin-right: 1mm;
        }

        #especialistas {
            width: 185mm;
        }

        #especialistas .foto-especialista {
            width: 58mm;
            height: 38mm;
            margin-left: 2mm;
            margin-bottom: 2mm
        }

        #especialistas .foto-especialista table {
            width: 28mm;
            border: 0.5mm solid white;
            color: white;
            margin-left: 1.8mm;
            margin-top: 1.8mm;
        }

        #especialistas .foto-especialista table .info-especialista {
            border-bottom: 0.5mm solid white;
            padding-left: 1.5mm;
            padding-right: 1.5mm;
            text-align: center;
            font-size: 8pt;
            height: 2cm;
        }

        .especialidad {
            font-weight: bold; font-family: 'bbvawebbook';
        }

        .nombre-especialista {
            padding-left: 1.5mm;
            padding-right: 1.5mm;
            text-align: center;
            font-size: 7pt;
            font-family: 'bbvawebbook';
            height: 1.35cm;
        }

        .pie-pagina-2 {
            margin-left: 2cm; margin-top: 0.7cm; font-size: 8pt;
        }

        /* -- PAGINA 3 -- */

        .imagen-pagina-3 {
            display: block;
            margin-left: 2.1cm;
            overflow: hidden;
            width: 25cm;
        }

        /* -- PAGINA INFORMACION -- */

        .info-oficina {
            width: 12.5cm;
            color: #005193;
            font-family: 'bbvawebbook';
            font-size: 12.6pt;
            border: 0.5mm solid #005193;
            padding-left: 5mm;
            padding-top: 3mm;
            padding-bottom: 3mm;
        }

        .celda-director {
            padding-left: 5mm;
            vertical-align: top
        }

        .celda {
            padding-top: 5mm;
            vertical-align: top
        }

        .cabecera-info {
            color: white;
            font-family: 'bbvawebbook';
            font-size: 12.6pt;
            padding-left: 5mm;
            padding-right: 10mm;
            vertical-align: middle;
        }

        .esquina-cabecera {
            display: inline-block;
            vertical-align: middle;
            width: 5.5mm;
        }


        .borde { width: 12.5cm; height: 1mm; font-size: 5px; }
        .borde-azul-1 { border-top: 0.3mm solid #005292; border-right: 0.3mm solid #005292; }
        .borde-azul-2 { border-top: 0.3mm solid #45B9E6; border-right: 0.3mm solid #45B9E6; }
        .borde-azul-3 { border-top: 0.3mm solid #9CD5F1; border-right: 0.3mm solid #9CD5F1; }
        .borde-azul-4 { border-top: 0.3mm solid #CDEAFB; border-right: 0.3mm solid #CDEAFB; }

        .padding-izq { padding-left: 5mm; }

        .info {
            font-family: 'bbvawebbook';
            font-size: 10pt;
            color: #005193;
            padding-left: 5mm;
            padding-top: 1.5mm;
            width: 62.5mm;
        }

        .cabecera-azul-1 { background: #005292; }
        .cabecera-azul-2 { background: #45B9E6; }
        .cabecera-azul-3 { background: #9CD5F1; }
        .cabecera-azul-4 { background: #CDEAFB; color: #45B9E6}

    </style>
</head>
<body>

<!--mpdf
<htmlpageheader name="myHTMLHeader1">
		<img src="<?=$baseUrl?>/assets_pdf/background.png" />
	</htmlpageheader>
	<sethtmlpageheader name="myHTMLHeader1" value="on" show-this-page="1" />mpdf-->

<!-- PAGINA 1 -->
<div class="wrapper-pagina-1" >
    <table style="text-align: center" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
            <?php
            $nombreEmpresa = trim(mb_strtoupper($datos_form['nombre_empresa']));
            $nombreEmpresa = $nombreEmpresa == '' ? '&nbsp;' : $nombreEmpresa;
            ?>
            <td class="nombre-empresa-principal" ><?=$nombreEmpresa?></td>
        </tr>
        <tr>
            <td class="frase-pagina-1" >
                <?=$str['pagina_1_titular'][$langId];?>
            </td>
        </tr>
        <tr>
            <td class="frase-2-pagina-1" >
                <?=$str['pagina_1_texto_1'][$langId];?>
            </td>
        </tr>
        <tr>
            <td class="frase-3-pagina-1" >
                <?=$str['pagina_1_texto_2'][$langId];?>
            </td>
        </tr>
        </tbody>
    </table>

    <table class="tabla-equipo-pagina-1" cellspacing="0" cellpadding="0" >
        <tr>
            <td class="cabecera-equipo" colspan="3"  ></td>
        </tr>
        <tr>
            <td class="equipo-director" >
                <?=$str['bloque_pagina_1_director_relacion'][$langId]?>
            </td>
            <td><img class="img_1_mas_9"  src="<?=$baseUrl?>/assets_pdf/1_mas_9.png" /></td>
            <td class="equipo-especialistas" ><?=$str['bloque_pagina_1_especialistas'][$langId]?></td>
        </tr>
        <tr>
            <td class="pie-equipo" colspan="3" >
                <?=$str['bloque_pagina_1_expertos'][$langId]?>
            </td>
        </tr>
    </table>
</div>

<pagebreak />

<!--mpdf
<htmlpageheader name="myHTMLHeader1">
		<img src="<?=$baseUrl?>/assets_pdf/background.png" />
	</htmlpageheader>
	<sethtmlpageheader name="myHTMLHeader1" value="on" show-this-page="1" />mpdf-->

<!-- PAGINA 2 -->
<div class="cabecera">
    <span class="nombre-empresa"><?= (trim($datos_form['nombre_empresa']) != '') ? mb_strtoupper($datos_form['nombre_empresa']) : '&nbsp;'?></span>
    <br>
    <span class="frase-2"><?=$str['pagina_2_titular'][$langId];?></span>
</div>
<div id="director_relacion">
    <div class="wrapper-background">
        <table width="50mm" cellpadding="0" cellspacing="0">
            <tr>
                <?php $trato = $datos_form['directorrelacionTrato'];?>
                <td class="cargo"><?=$str['pagina_2_texto_director_'.$trato][$langId];?></td>
                <td class="nombre"><?=mb_strtoupper($datos_form['directorrelacionNombre'] . ' ' .$datos_form['directorrelacionApellido1'] . ' ' . $datos_form['directorrelacionApellido2']);?></td>
            </tr>
            <?php if($datos_form['directorrelacionMovil'] != ''):?>
            <tr>
                <td colspan="2" class="info-contacto">
                    <img class="icono" src="<?=$baseUrl?>/assets_pdf/icono_telefono.png" /> <?= $datos_form['directorrelacionMovil']?>
                </td>
            </tr>
            <?php endif;?>
            <?php if($datos_form['directorrelacionEmail'] != ''):?>
            <tr>
                <td colspan="2" class="info-contacto">
                    <img class="icono" src="<?=$baseUrl?>/assets_pdf/icono_email.png" /> <?= $datos_form['directorrelacionEmail']?>
                </td>
            </tr>
            <?php endif;?>
        </table>
    </div>
</div>

<div id="especialistas">
    <?php foreach($especialistas as $idEspecialidad => $especialista):
        $info_especialidad = array(
            $str['especialista_en'][$langId],
            "<br/>",
            "<span class='especialidad'>".mb_strtoupper($especialidades[$idEspecialidad][$langId])."</span>"
        );
        if ($langId == '3') {
            $info_especialidad = array_reverse($info_especialidad);
        }
        ?>
        <div class="foto-especialista" style="background: url(<?=$especialista['foto'];?>);">
            <table cellspacing="0">
                <tr>
                    <td class="info-especialista">
                        <?=implode(' ',$info_especialidad);?>
                    </td>
                </tr>
                <tr>
                    <td class="nombre-especialista">
                        <?= mb_strtoupper($especialista['nombre'] . ' ' . $especialista['apellido1'] . ' ' . $especialista['apellido2']);?>
                    </td>
                </tr>
            </table>
        </div>
    <?php endforeach;?>
</div>

<div class="pie-pagina-2">
    <?=$str['pagina_2_pie'][$langId];?>
</div>

<pagebreak />

<!--mpdf
<htmlpageheader name="myHTMLHeader1">
		<img src="<?=$baseUrl?>/assets_pdf/background.png" />
	</htmlpageheader>
	<sethtmlpageheader name="myHTMLHeader1" value="on" show-this-page="1" />mpdf-->

<!-- PAGINA 3 -->
<div class="cabecera">
    <span class="nombre-empresa"><?= (trim($datos_form['nombre_empresa']) != '') ? mb_strtoupper($datos_form['nombre_empresa']) : '&nbsp;'?></span>
    <br>
    <span class="frase-3"><?=$str['pagina_3_titular'][$langId];?></span>
</div>

<div class="imagen-pagina-3">
    <img src="<?=$baseUrl?>/assets_pdf/pagina_3_lang_<?=$langId?>.jpg" />
</div>

<?php if((bool) $datos_form['generaroficina']) :?>
<pagebreak />

<!--mpdf
<htmlpageheader name="myHTMLHeader1">
		<img src="<?=$baseUrl?>/assets_pdf/background.png" />
	</htmlpageheader>
	<sethtmlpageheader name="myHTMLHeader1" value="on" show-this-page="1" />mpdf-->

<!-- PAGINA 4 -->

    <div class="cabecera cabecera-1">
        <span class="nombre-empresa"><?= (trim($datos_form['nombre_empresa']) != '') ? mb_strtoupper($datos_form['nombre_empresa']) : '&nbsp;'?></span>
        <br>
        <span class="frase-4"><?=$str['pagina_4_titular'][$langId];?></span>
    </div>


    <table border="0" cellpadding="0" cellspacing="0" style="font-size: 18pt; margin-left: 2.1cm;">
        <tr>
            <td class="info-oficina">
                <?=$datos_form['oficinaNombre']?> <?=$datos_form['oficinaNumero']?> <br>
                <?=$datos_form['oficinaDireccion']?><br>
                <?=$datos_form['oficinaLocalidad']?> <?=$datos_form['oficinaCp']?> <br>
                <?=$datos_form['oficinaProvincia']?>
            </td>
            <td class="celda-director azul-oscuro">
                <?php

                $infoDirector = $datos_form['director'];

                $directorOficina = trim($infoDirector['do_nombre']);
                $telefonoDirectorOficina = trim($infoDirector['do_telefono']);
                $emailDirectorOficina = trim($infoDirector['do_email']);

                if($directorOficina != ''):?>
                    <table cellspacing="0" cellpadding="0" width="10cm">
                        <tr>
                            <td>
                                <table cellspacing="0" cellpadding="0">
                                    <tr>
                                        <td class="cabecera-info cabecera-azul-1">
                                            <?=$str['pagina_4_director_oficina'][$langId];?>
                                        </td>
                                        <td>
                                            <img
                                                class="esquina-cabecera"
                                                src="<?=$baseUrl?>/assets_pdf/borde-cabecera-1.gif"
                                                />
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td class="borde borde-azul-1">&nbsp;</td>
                        </tr>
                        <tr>
                            <td class="info">
                                <?= $directorOficina?> <br>
                                <?php if($telefonoDirectorOficina != ''):?>
                                    <?=$str['pagina_4_telefono'][$langId];?> <?=$telefonoDirectorOficina?> <br>
                                <?php endif;?>
                                <?php if($emailDirectorOficina != ''):?>
                                    <?=$emailDirectorOficina;?>
                                <?php endif;?>
                            </td>
                        </tr>
                    </table>
                <?php endif;?>
            </td>
        </tr>

        <?php foreach($page_info_data as $tabIndex => $tab):?>
            <?=$tab['html'];?>
        <?php endforeach;?>

    </table>

<?php endif;?>
</body>
</html>