<?php

if (is_null($this->menu)) {
    die;
}

$assetPath = $this->basePath('absconsultor');
$menuHelper       = $this->applicationMenuHelper();
$socialIconHelper = $this->socialIconHelper();
$legalLinkHelper  = $this->legalLinkHelper();
$menu = $this->menu;

echo $this->doctype(); ?>

<html lang="<?=$this->lang?>">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle();?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.jpg'])
            ->prependStylesheet($assetPath . '/css/style.css?t=' . microtime())
            //->prependStylesheet($assetPath . '/css/bootstrap.css')
            ->prependStylesheet($assetPath . '/css/magnific-popup.css')
            ->prependStylesheet($assetPath . '/css/tiny-slider.css')
            ->prependStylesheet($assetPath . '/css/simple-line-icons.css')
            ->prependStylesheet($assetPath . '/css/icomoon.css')
            ->prependStylesheet($assetPath . '/css/animate.css')
            ->prependStylesheet('https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600,400italic,700');
        ?>

        <meta name="theme-color" content="#00344F">

        <?php if (isset($this->og)) {
            $this->OpenGraphTag()->render($this->og);
        }?>

        <script src="<?=$assetPath . '/js/modernizr-2.6.2.min.js';?>"></script>
    </head>
    <body>


    <header role="banner" id="abstpl-header">
        <div class="container">
            <nav class="navbar navbar-default">
                <div class="navbar-header">
                    <!-- Mobile Toggle Menu Button -->
                    <a id="js-abstpl-nav-toggle" class="js-abstpl-nav-toggle abstpl-nav-toggle" data-toggle="collapse" data-target="#navbar"
                       aria-expanded="false" aria-controls="navbar"><i></i></a>
                    <a class="navbar-brand gotop" href="#">
                        <img src="<?=$assetPath . '/images/logo.png';?>" alt="company-logo" class="main-logo">
                        <img src="<?=$assetPath . '/images/logo2.png';?>" alt="company-logo" class="secondary-logo">
                    </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <?php if(!is_null($this->menu)):?>
                            <?=$menuHelper->render($this->menu,$this->lang);?>
                            <?php foreach($this->languages as $langForFlag):?>
                                <li class="lang"><a href="/<?=$langForFlag->code;?>"><span class="flag-icon <?=$langForFlag->code?>"></span> </a></li>
                            <?php endforeach?>
                        <?php endif;?>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <?php echo $this->content ?>

    <footer id="footer" role="contentinfo">
        <a href="#" class="gotop" id="js-gotop"><i class="icon-arrow-up2"></i></a>
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <p>&copy; <?=$this->appData->row->companyName;?></p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <ul class="social social-circle">
                        <?php if(!is_null($this->appData)):?>
                            <?php echo $socialIconHelper->render($this->appData->row);?>
                        <?php endif;?>
                    </ul>
                </div>

                <?php /*$legalLinkHelper->render($this->legal,$this->lang);*/?>
            </div>
            <div class="row hide">
                <div class="col-md-12 text-center small">
                    This site is protected by reCAPTCHA and the Google
                    <a target="_blank" href="https://policies.google.com/privacy">Privacy Policy</a> and
                    <a target="_blank" href="https://policies.google.com/terms">Terms of Service</a> apply.
                </div>
            </div>
        </div>
    </footer>

    <?php if ($this->showCookieAlert) :?>
        <div id="cookie_alert" class="hide container-fluid">
            <div class="col-md-12">
                <?=$this->translate('Cookie message','frontend');?>
                <a data-toggle="modal" data-target="#popupCookies" href="#"><?=$this->translate('More info','frontend');?></a>
                &nbsp;&nbsp;&nbsp;
                <a href="#" id="close_cookie_alert"><?=$this->translate('Cookies agree','frontend');?></a>
            </div>
        </div>
    <?php endif; ?>

    <input type="hidden" id="simple-routing-manager" name="<?=$this->srmController;?>" value="<?=$this->controllerAction;?>" />

    <!-- Scripts -->
    <script src="https://www.google.com/recaptcha/api.js?render=6LdGVMwUAAAAALwwx1GI2tM5ECgIABu9zXxkxogh"></script>
    <input type="hidden" id="google-captcha-key" value="6LdGVMwUAAAAALwwx1GI2tM5ECgIABu9zXxkxogh">

    <?php echo $this->headScript()
            ->appendFile($assetPath. '/dist/vendor-dist.js')
            ->appendFile($assetPath. '/dist/dist.js')
        ; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
