<?php

$menuHelper       = $this->applicationMenuHelper();
$socialIconHelper = $this->socialIconHelper();
$legalLinkHelper  = $this->legalLinkHelper();

echo $this->doctype(); ?>

<html lang="<?=$lang?>">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle();?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.jpg'))
                        ->prependStylesheet($this->basePath('absconsultor/dist/css/css-dist.css'))
                        ->prependStylesheet('https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700|Open+Sans')
        ?>
        <meta name="theme-color" content="#00344F">
    </head>
    <body>
        <nav class="navbar navbar-fixed-top transition not-visible" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url($lang,array('lang' => $lang)) ?>">
                        <img class="hidden-xs" width="100" src="<?php echo $this->basePath('img/white-logo.png') ?>" alt="Logo ABS Consultor"/>
                        <img class="visible-xs" width="169" src="<?php echo $this->basePath('img/white-logo-horizontal.png') ?>" alt="Logo ABS Consultor"/>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?=$menuHelper->render($menu,$lang);?>
                        <li class="lang"><a href="/es_es"><span class="flag-icon flag-icon-es"></span> </a></li>
                        <li class="lang"><a href="/en_en"><span class="flag-icon flag-icon-gb"></span> </a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid abs">

            <?php echo $this->content; ?>

        </div> <!-- /container -->

        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-right contact-info">
                        <div class="row">
                            <div class="col-md-12">
                                <p><?=$this->translate('Follow us','frontend');?></p>
                                <div class="contact-icons">
                                    <?=$socialIconHelper->render($appData->row);?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p><?=$this->translate('Contact us','frontend');?></p>
                                <div class="contact-icons">
                                    <a class="phone" href="tel:<?=$appData->locale->{$lang}->phone?>"><?=$appData->locale->{$lang}->phone?> <i class="social-icon fa fa-phone"></i></a>
                                    <a class="mail" href="mailto:<?=$appData->locale->{$lang}->email?>"><?=$appData->locale->{$lang}->email?> <i class="social-icon fa fa-envelope"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <?php $legalLinkHelper->render($legal,$lang);?>
                    </div>
                </div>
            </div>

        </footer>
        <?php if ($showCookieAlert) :?>
            <div id="cookie_alert" class="hide container-fluid">
                <div class="col-md-12">
                    <?=$this->translate('Cookie message','frontend');?>
                    <a href="<?=$this->url($lang.'/legal/page',array('page' => 'cookies'));?>"><?=$this->translate('More info','frontend');?></a>
                    &nbsp;&nbsp;&nbsp;
                    <a href="#" id="close_cookie_alert"><?=$this->translate('Cookies agree','frontend');?></a>
                </div>
            </div>
        <?php endif; ?>
        <input type="hidden" id="simple-routing-manager" name="<?=$srmController;?>" value="<?=$controllerAction;?>" />
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath('absconsultor/dist/vendor-dist.js'))
            ->appendFile($this->basePath('absconsultor/dist/dist.js'))

        ; ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
