<?php

/**
 * VARIABLES DISPONIBLES
 *      $this (es una instancia de zend-view/src/Renderer/PhpRenderer.php)
 *      $element
 *      $label
 *      $labelAttributes
 *      $labelPosition
 *      $renderErrors
 */

$imagesUrl = $element->getValue();

$html = '';

$formInput = $this->formInput();
$element->setName($element->getName().'[]');
$element->setAttribute('data-is-multiple','1');
$row = "<div class = 'form-group'><div class='col-xs-12'>%s</div></div>";

$id = $element->getAttribute('id');

if (count($imagesUrl)) {
    foreach ($imagesUrl as $index => $url) {
        $element->setValue($url);

        $element->setAttribute('id',$id.$index);
        $element->setAttribute('data-id',$id);

        $html .= sprintf($row,$formInput->render($element));
    }
} else {
    $element->setValue('');
    $html .= sprintf($row,$formInput->render($element));
}

echo $html . '<input type = "button" class="pull-right btn btn-info btn-flat allow_multiple_files" value="Nueva imagen" data-value="'.$id.'" />';