<div class="row home-background" style="height: 100vh;">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Manual de usuario</h3>
            </div>
            <div class="box-body">
                <div class="box-group" id="menu_accordion">
                    <div class="panel box box-success collapsed-box" data-id="224">
                        <div class="box-header">
                            <h4 class="box-title">
                                <a data-toggle="collapse" data-parent="#menu_accordion" href="#collapse0">
                                    Web Menú
                                </a>
                            </h4>
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="box-body">
                            <p>Desde aquí podemos editar ciertos aspectos de las secciones principales de la web</p>
                            <p>Dichas secciones son: </p>
                            <ul>
                                <li>Empresa</li>
                                <li>Colaboradores (que está dentro de empresa)</li>
                                <li>Contacto</li>
                                <li>Trabajos</li>
                            </ul>
               
             <p>Los campos que podemos editar son los siguientes:</p>
                            <ul>
                                <li><strong>Clave</strong> Clave única que identifica nuestro registro de sección.
                                    Debe ser descriptiva y nombre debe estar relacionado con los datos que vamos
                                a guardar en el registro</li>
                                <li>
                                    <strong>Visible</strong>: Si está marcado como "Sí", el enlace a la sección
                                    se mostrará en la cabecera de la web.
                                </li>
                                <li>
                                    <strong>Active</strong>. Indica si el enlace está disponible o no. La diferencia
                                    entre "visible" y "activo" es que, si marcamos el enlace como "no visible", el
                                    acceso a la sección sigue estando disponible, aunque en principio no haya ningún
                                    enlace apuntando hacia ella. En cambio, si está desactivada e intentamos acceder
                                    a ella, la web nos dará un error 404 (página no encontrada), porque se entiende
                                    que la página en cuestión no existe.
                                </li>
                                <li>
                                    <strong>Posición</strong>: Orden que llevarán los enlaces del menú. Se pinta de
                                    izquierda a derecha.
                                </li>
                                <li>
                                    <strong>Nombre</strong>: Nombre que se mostrará como cabecera cuando accedemos a la sección
                                </li>
                                <li><strong>Nombre cabecera</strong>: Nombre que se mostrará en el menú de la cabecera</li>
                                <li>
                                    <strong>Contenido</strong>: Lo que escribamos aquí se reflejará en su sección correspondiente
                                    En nuestro caso, por ejemplo, si accedemos a la edición del texto de "company", podremos
                                    modificar el texto que se muestra en la sección "empresa" de la web
                                </li>
                                <li>
                                    <strong>Segmento url</strong>: Este campo es muy importante, tanto para las secciones
                                    principales como el resto de subsecciones. Su designación debe ser pensaba a conciencia,
                                    ya que es el texto que se usará para formas las direcciones web únicas.
                                    <p>
                                        Por ejemplo: Si el segmento url que designamos a la sección "empresa" se llama
                                        consultor-abs-empresa, el enlace que se forma para acceder a dicha sección tendrá
                                        la siguiente forma: <strong>http://absconsultor.es/es_es/consultor-abs-empresa</strong>
                                        Esta es la forma por la que el sistema sabe a qué sección queremos ir.
                                    </p>
                                </li>
                                <li>
                                    <strong>Descripción interna (SEO)</strong>: El contenido que introduzcamos aquí no se verá
                                    directamente en la web pero es igual de importante que si lo vieramos. Su redacción debe
                                    cuidarse al máximo ya que ayuda al correcto posicionamiento de la web. Además, será
                                    el texto que se muestre como descripción cuando compartamos la url por Facebook.
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="panel box box-success collapsed-box" data-id="230">
                        <div class="box-header">
                            <h4 class="box-title">
                                <a data-toggle="collapse" data-parent="#menu_accordion" href="#collapse2">
                                    Datos Web
                                </a>
                            </h4>
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="box-body">
                            Datos genéricos de nuestra web. Desde aquí podremos editar:
                            <ul>
                                <li><strong>Email inbox</strong> Dirección de correo a la que
                                llegaran los mensajes de la gente que contacte por mail</li>
                                <li><strong>Página de Facebook</strong> Página oficial de la empresa en Facebook (si tuviese)</li>
                                <li><strong>Página de Twitter</strong> Página oficial de la empresa en Twitter (si tuviese)</li>
                                <li><strong>Página de Google+ </strong> Página oficial de la empresa en Google+(si tuviese)</li>
                                <li><strong>Página de Instagram</strong> Página oficial de la empresa en Instagram (si tuviese)</li>
                                <li><strong>Email</strong> Correo que se muestra en el footer de la web y en la sección de contacto</li>
                                <li><strong>Teléfono</strong> Teléfono que se muestra en el footer de la web y en la sección de contacto</li>
                            </ul>
                        </div>
                    </div>
                    <div class="panel box box-success collapsed-box" data-id="231">
                        <div class="box-header">
                            <h4 class="box-title">
                                <a data-toggle="collapse" data-parent="#menu_accordion" href="#collapse3">
                                    Colaboradores
                                </a>
                            </h4>
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="box-body">
                            Gestión de los colaboradores asociados a ABS Consultor. Podremos, añadir, editar o eliminar
                            colaboradores. Los campos a editar son los siguientes:
                            <ul>
                                <li><strong>Nombre</strong>: Nombre de la empresa colaboradora</li>
                                <li>
                                    <strong>Logotipo</strong>: Imagen de la empresa colaboradora (será la que se visualize en carrusel de
                                    imágenes de la sección empresa
                                </li>
                                <li><strong>Website</strong>: Sitio web de la empresa colaboradora</li>
                                <li><strong>Activo:</strong>: Activar o desactivar una empresa colaboradora</li>
                                <li><strong>Contenido:</strong>: Breve descripción de la empresa</li>
                            </ul>
                        </div>
                    </div>
                    <div class="panel box box-success collapsed-box" data-id="219">
                        <div class="box-header">
                            <h4 class="box-title">
                                <a data-toggle="collapse" data-parent="#menu_accordion" href="#collapse5">
                                    Trabajos
                                </a>
                            </h4>
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="box-body">
                            <p>
                                Para dar de alta un trabajo, es necesario asignarle una <strong>categoría</strong>. Para acceder
                                a la gestión de categorías, deplegamos el menú "Trabajos" y pulsamos sobre el
                                boton "Categorías". Los campos de categoría que podemos editar son los siguientes:
                            </p>
                            <ul>
                                <li><strong>Clave</strong>: Nombre único que distingue la categoría del resto</li>
                                <li><strong>Activo</strong>: Activar o desactivar una categoría. <strong>Importante:</strong>
                                Si desactivamos una categoría que tiene trabajos asociados, dichos trabajos pasarán
                                a estar desactivados tambíen, por lo que si intentamos acceder a ellos, la web nos
                                dará un error 404 (Página no encontrada)
                                </li>
                                <li><strong>Título</strong>: Nombre de la categoría. Dicho nombre será el que aparezca
                                en el lateral derecho del listado de trabajos y como sub título en el detalle de un
                                trabajo</li>
                            </ul>

                            <p>Una vez tengamos lista al menos una categoría, podremos dar de alta nuestros trabajos.
                            Los campos de la sección trabajos que podremos editar son los siguientes:</p>

                            <ul>
                                <li><strong>Categoría</strong>: Categoría a la que pertenecerá nuestro trabajo</li>
                                <li><strong>Clave</strong>: Nombre único que distingue a un trabajo del resto</li>
                                <li>Url Media: Imágen o video de youtube que podremos asociar a nuestro trabajo
                                    Podemos añadir más de 1 archivo o video de youtube</li>
                                <li><strong>Activo</strong>: Activar o desactivar el trabajo</li>
                                <li><strong>Título</strong>: Título del trabajo</li>
                                <li><strong>Segmento url</strong>: Este campo será una cadena de texto que identifica
                                nuestro trabajo dentro de la url. Nunca podrá existir dos trabajos con el mismo valor
                                    en su segmento url.</li>
                                <li><strong>Contenido</strong>: Texto descriptivo de nuestro trabajo</li>
                                <li>
                                    <strong>Descripción interna (SEO)</strong>: El contenido que introduzcamos aquí no se verá
                                    directamente en la web pero es igual de importante que si lo vieramos. Su redacción debe
                                    cuidarse al máximo ya que ayuda al correcto posicionamiento de la web. Además, será
                                    el texto que se muestre como descripción cuando compartamos la url por Facebook.
                                </li>
                            </ul>

                        </div>
                    </div>
                    <div class="panel box box-success collapsed-box" data-id="215">
                        <div class="box-header">
                            <h4 class="box-title">
                                <a data-toggle="collapse" data-parent="#menu_accordion" href="#collapse8">
                                    Media
                                </a>
                            </h4>
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="box-body">
                            <p>
                                La sección media es la que nos facilita la gestión de los archivos
                                de multimedia que posteriormente asociaremos a las distintas secciones de
                                la web que puedan (o requieran) tener algún archivo de imagen.
                                Su funcionamiento es similar al explorador de archivos de windows,
                                pudiendo crear/eliminar/renombrar carpetas para incluir los archivos en ellas.
                                Desde aquí, además, deberemos subir los videos que iran al canal de youtube.
                            </p>
                        </div>
                    </div>
                    <div class="panel box box-success collapsed-box" data-id="218">
                        <div class="box-header">
                            <h4 class="box-title">
                                <a data-toggle="collapse" data-parent="#menu_accordion" href="#collapse9">
                                    Páginas Legales
                                </a>
                            </h4>
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="box-body">

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>